// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.
// Generated groups of the helmstudio runtime SDK. Import from ./index.js.

export const API_VERSION = "1.0.0";

/** The me group. */
export class MeGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Who the token belongs to, what it may do, and how much quota is left. (GET /me) */
  get() {
    return this.t.request("GET", "/me", { query: {}, headers: {}, expect: "json" });
  }
}

/** The events group. */
export class EventsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Server-sent events for the calling studio. (GET /events) */
  subscribe(params = {}) {
    return this.t.request("GET", "/events", { query: {}, headers: {"Last-Event-ID": params.lastEventId}, expect: "sse" });
  }
}

/** The kv group. */
export class KVGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** List keys in a namespace, with sizes and modified times. No values. (GET /kv/{ns}) */
  list(ns, params = {}) {
    return this.t.request("GET", "/kv/" + encodeURIComponent(ns), { query: {"prefix": params.prefix, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Read one document. (GET /kv/{ns}/{key}) */
  get(ns, key) {
    return this.t.request("GET", "/kv/" + encodeURIComponent(ns) + "/" + encodeURIComponent(key), { query: {}, headers: {}, expect: "json" });
  }

  /** Create or replace a document. (PUT /kv/{ns}/{key}) */
  put(ns, key, body, params = {}) {
    return this.t.request("PUT", "/kv/" + encodeURIComponent(ns) + "/" + encodeURIComponent(key), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Apply a JSON merge patch (RFC 7396) to an existing document. (PATCH /kv/{ns}/{key}) */
  patch(ns, key, body, params = {}) {
    return this.t.request("PATCH", "/kv/" + encodeURIComponent(ns) + "/" + encodeURIComponent(key), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Remove a document. (DELETE /kv/{ns}/{key}) */
  delete(ns, key, params = {}) {
    return this.t.request("DELETE", "/kv/" + encodeURIComponent(ns) + "/" + encodeURIComponent(key), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "empty" });
  }
}

/** The sessions group. */
export class SessionsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The calling studio's sessions, most recently opened first. (GET /sessions) */
  list(params = {}) {
    return this.t.request("GET", "/sessions", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Create a session. (POST /sessions) */
  create(body) {
    return this.t.request("POST", "/sessions", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** One session. A deleted session, or another studio's, is 404. (GET /sessions/{id}) */
  get(id) {
    return this.t.request("GET", "/sessions/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Rename, or merge changes into the state document. (PATCH /sessions/{id}) */
  update(id, body, params = {}) {
    return this.t.request("PATCH", "/sessions/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Soft-delete. Its name becomes free; items keep their session_id. (DELETE /sessions/{id}) */
  delete(id, params = {}) {
    return this.t.request("DELETE", "/sessions/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "empty" });
  }

  /** Copy a session's state under a new name. The copy has never been opened. (POST /sessions/{id}:duplicate) */
  duplicate(id, body) {
    return this.t.request("POST", "/sessions/" + encodeURIComponent(id) + ":duplicate", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Set opened_at to now. Changes neither the state nor the etag, nor any process. (POST /sessions/{id}:activate) */
  activate(id) {
    return this.t.request("POST", "/sessions/" + encodeURIComponent(id) + ":activate", { query: {}, headers: {}, expect: "empty" });
  }
}

/** The records group. */
export class RecordsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Query a collection with the closed filter language. Never SQL. (GET /records/{collection}) */
  query(collection, params = {}) {
    return this.t.request("GET", "/records/" + encodeURIComponent(collection), { query: {"where": params.where, "order": params.order, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Insert a document; returns its id and etag. (POST /records/{collection}) */
  insert(collection, body) {
    return this.t.request("POST", "/records/" + encodeURIComponent(collection), { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** One record. Deleted, in another collection, or another studio's is 404. (GET /records/{collection}/{id}) */
  get(collection, id) {
    return this.t.request("GET", "/records/" + encodeURIComponent(collection) + "/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Replace a document. If-Match on the etag; 409 on conflict. (PUT /records/{collection}/{id}) */
  replace(collection, id, body, params = {}) {
    return this.t.request("PUT", "/records/" + encodeURIComponent(collection) + "/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Apply a JSON merge patch (RFC 7396). If-Match on the etag; 409 on conflict. (PATCH /records/{collection}/{id}) */
  patch(collection, id, body, params = {}) {
    return this.t.request("PATCH", "/records/" + encodeURIComponent(collection) + "/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Soft-delete, so an undo is possible and a sync never sees a gap. (DELETE /records/{collection}/{id}) */
  delete(collection, id, params = {}) {
    return this.t.request("DELETE", "/records/" + encodeURIComponent(collection) + "/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "empty" });
  }
}

/** The assets group. */
export class AssetsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Upload bytes. Idempotent on content. (POST /assets) */
  upload(body, contentType, params = {}) {
    return this.t.request("POST", "/assets", { query: {"kind": params.kind, "filename": params.filename, "pinned": params.pinned, "width": params.width, "height": params.height, "duration_s": params.durationS, "fps": params.fps}, headers: {}, expect: "json", raw: body, contentType });
  }

  /** Adopt a file from the stage or data directory by hardlink — no copy, no HTTP body. (POST /assets:adopt) */
  adopt(body) {
    return this.t.request("POST", "/assets:adopt", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** The asset's bytes, with Range. (GET /assets/{id}) */
  read(id, params = {}) {
    return this.t.request("GET", "/assets/" + encodeURIComponent(id), { query: {}, headers: {"Range": params.range}, expect: "raw" });
  }

  /** A thumbnail, generated once and cached. (GET /assets/{id}/thumb) */
  thumb(id, params = {}) {
    return this.t.request("GET", "/assets/" + encodeURIComponent(id) + "/thumb", { query: {"w": params.w}, headers: {}, expect: "raw" });
  }

  /** Downstream provenance — every item ever made from this asset, recursively. (GET /assets/{id}/lineage) */
  lineage(id, params = {}) {
    return this.t.request("GET", "/assets/" + encodeURIComponent(id) + "/lineage", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }
}

/** The gallery group. */
export class GalleryGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Record an output with its params, inputs, tags and session. One call per generation. (POST /gallery/items) */
  add(body) {
    return this.t.request("POST", "/gallery/items", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Query items, scoped to the caller unless scope=all. (GET /gallery/items) */
  query(params = {}) {
    return this.t.request("GET", "/gallery/items", { query: {"scope": params.scope, "studio": params.studio, "kind": params.kind, "tag": params.tag, "session_id": params.sessionId, "starred": params.starred, "asset_id": params.assetId, "since": params.since, "until": params.until, "q": params.q, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One item. Another studio's without gallery.read_all, or a deleted one, is 404. (GET /gallery/items/{id}) */
  get(id) {
    return this.t.request("GET", "/gallery/items/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Star, tag or rename one of the caller's own items. (PATCH /gallery/items/{id}) */
  update(id, body) {
    return this.t.request("PATCH", "/gallery/items/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Soft-delete one of the caller's own items. (DELETE /gallery/items/{id}) */
  delete(id) {
    return this.t.request("DELETE", "/gallery/items/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "empty" });
  }

  /** Upstream provenance — the items whose outputs this item was made from, recursively. (GET /gallery/items/{id}/lineage) */
  lineage(id, params = {}) {
    return this.t.request("GET", "/gallery/items/" + encodeURIComponent(id) + "/lineage", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }
}

/** The handoff group. */
export class HandoffGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Put an item in another studio's inbox. (POST /handoff) */
  send(body) {
    return this.t.request("POST", "/handoff", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The inbox group. */
export class InboxGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Handoffs to the caller not yet consumed, oldest first. (GET /inbox) */
  list(params = {}) {
    return this.t.request("GET", "/inbox", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Mark an entry handled. Idempotent. (POST /inbox/{id}:consume) */
  consume(id) {
    return this.t.request("POST", "/inbox/" + encodeURIComponent(id) + ":consume", { query: {}, headers: {}, expect: "empty" });
  }
}

/** The jobs group. */
export class JobsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The calling studio's jobs, of every kind, newest first. (GET /jobs) */
  list(params = {}) {
    return this.t.request("GET", "/jobs", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Report a long-running piece of the studio's own work as a task job. (POST /jobs) */
  create(body) {
    return this.t.request("POST", "/jobs", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** One of the calling studio's jobs. Another studio's is 404. (GET /jobs/{id}) */
  get(id) {
    return this.t.request("GET", "/jobs/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Report progress on, or finish, a task job the calling studio created. (PATCH /jobs/{id}) */
  update(id, body) {
    return this.t.request("PATCH", "/jobs/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Ask for one of the calling studio's task jobs to be cancelled. (POST /jobs/{id}:cancel) */
  cancel(id) {
    return this.t.request("POST", "/jobs/" + encodeURIComponent(id) + ":cancel", { query: {}, headers: {}, expect: "empty" });
  }

  /** One of the calling studio's job logs as server-sent events, from the start, then live until the job finishes. (GET /jobs/{id}/logs) */
  logs(id) {
    return this.t.request("GET", "/jobs/" + encodeURIComponent(id) + "/logs", { query: {}, headers: {}, expect: "sse" });
  }

  /** Append lines to a running task job's log. (POST /jobs/{id}/logs) */
  appendLog(id, body) {
    return this.t.request("POST", "/jobs/" + encodeURIComponent(id) + "/logs", { query: {}, headers: {}, expect: "empty", json: body, contentType: "application/json" });
  }
}

/** The timeline group. */
export class TimelineGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Create a sequence from clips, or from whole tracks. (POST /timeline) */
  create(body) {
    return this.t.request("POST", "/timeline", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** The sequences the caller may read, newest first. (GET /timeline) */
  list(params = {}) {
    return this.t.request("GET", "/timeline", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One sequence. One the caller may not read is 404. (GET /timeline/{id}) */
  get(id) {
    return this.t.request("GET", "/timeline/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Edit a sequence. Every edit is a revision. (PATCH /timeline/{id}) */
  update(id, body, params = {}) {
    return this.t.request("PATCH", "/timeline/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Delete a sequence. Its exports and their lineage stay. (DELETE /timeline/{id}) */
  delete(id, params = {}) {
    return this.t.request("DELETE", "/timeline/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "empty" });
  }

  /** The sequence's earlier revisions, newest first. (GET /timeline/{id}/revisions) */
  revisions(id, params = {}) {
    return this.t.request("GET", "/timeline/" + encodeURIComponent(id) + "/revisions", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Write an earlier revision back as the newest one. (POST /timeline/{id}:revert) */
  revert(id, body, params = {}) {
    return this.t.request("POST", "/timeline/" + encodeURIComponent(id) + ":revert", { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Add one asset to the end of a track, without stealing focus. (POST /timeline:append) */
  append(body) {
    return this.t.request("POST", "/timeline:append", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Ask the framework to show its editor on this sequence. (POST /timeline/{id}:open) */
  open(id) {
    return this.t.request("POST", "/timeline/" + encodeURIComponent(id) + ":open", { query: {}, headers: {}, expect: "json" });
  }

  /** Which path an export would take, and why. (GET /timeline/{id}:plan) */
  plan(id, params = {}) {
    return this.t.request("GET", "/timeline/" + encodeURIComponent(id) + ":plan", { query: {"preset": params.preset}, headers: {}, expect: "json" });
  }

  /** Export the sequence. Answers with the job that renders it. (POST /timeline/{id}:export) */
  export(id, body) {
    return this.t.request("POST", "/timeline/" + encodeURIComponent(id) + ":export", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** The sequence's export jobs, newest first. (GET /timeline/{id}/exports) */
  exports(id, params = {}) {
    return this.t.request("GET", "/timeline/" + encodeURIComponent(id) + "/exports", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Stop a running export and leave nothing behind. (POST /timeline/{id}/exports/{job}:cancel) */
  cancelExport(id, job) {
    return this.t.request("POST", "/timeline/" + encodeURIComponent(id) + "/exports/" + encodeURIComponent(job) + ":cancel", { query: {}, headers: {}, expect: "empty" });
  }
}

/** One property per API group, the same names as the Go and Python clients. */
export class Client {
  constructor(transport) {
    this.me = new MeGroup(transport);
    this.events = new EventsGroup(transport);
    this.kv = new KVGroup(transport);
    this.sessions = new SessionsGroup(transport);
    this.records = new RecordsGroup(transport);
    this.assets = new AssetsGroup(transport);
    this.gallery = new GalleryGroup(transport);
    this.handoff = new HandoffGroup(transport);
    this.inbox = new InboxGroup(transport);
    this.jobs = new JobsGroup(transport);
    this.timeline = new TimelineGroup(transport);
  }
}
