// helmstudio's runtime SDK for Node: a client for the platform API.
//
//   import { fromEnv } from "@helmstudio/runtime";
//   const helm = fromEnv();
//   const asset = await helm.assets.adopt({ path: out, kind: "video" });
//   await helm.gallery.add({ kind: "video", asset_id: asset.id, params: { seed: 42 } });
//
// Remote only (docs/design/04-packages.md §4). Method names match the Go and
// Python clients. generated.js is generated by api/gen; the rest is by hand.

import { API_VERSION, Client } from "./generated.js";
import { HelmError, Transport } from "./transport.js";

export { API_VERSION, Client, HelmError, Transport };

export function remote(base, token, options) {
  return new Client(new Transport(base, token, options));
}

export function fromEnv(env = globalThis.process ? globalThis.process.env : {}) {
  if (!env.HELM_API) throw new HelmError(0, "no_provider", "HELM_API is not set; run under helmstudio or helm dev");
  if (!env.HELM_TOKEN) {
    throw new HelmError(0, "no_token", "HELM_API is set but HELM_TOKEN is not; a studio with no capabilities gets no token");
  }
  return remote(env.HELM_API, env.HELM_TOKEN);
}
