-- Migration 1: the platform tables, verbatim from docs/design/02-data-model.md §5
-- (lines 272-357 at commit e8920ff). Do not edit this file: a schema change is a
-- new, higher-numbered migration. See docs/decisions.md, M1 foundation.

-- sessions: every studio has this concept, so the platform owns it rather than each
-- studio inventing a directory convention. This is what replaces sessions/*/setting.json.
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  studio_id TEXT NOT NULL,
  name TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT '{}',   -- the studio's own shape: prompt, seed, dims, refs…
  etag TEXT NOT NULL,                 -- optimistic concurrency for two open tabs
  created_at INTEGER NOT NULL, opened_at INTEGER, deleted_at INTEGER);
CREATE UNIQUE INDEX uq_session_name ON sessions(studio_id, name) WHERE deleted_at IS NULL;
CREATE INDEX idx_session_recent ON sessions(studio_id, opened_at DESC) WHERE deleted_at IS NULL;

-- singleton studio state: UI preferences, last opened session, panel widths
CREATE TABLE kv (
  studio_id TEXT, ns TEXT, key TEXT,
  doc TEXT NOT NULL, etag TEXT NOT NULL, updated_at INTEGER NOT NULL,
  PRIMARY KEY (studio_id, ns, key)) WITHOUT ROWID;

-- domain documents helmstudio deliberately does not model
CREATE TABLE records (
  id TEXT PRIMARY KEY, studio_id TEXT NOT NULL, collection TEXT NOT NULL,
  doc TEXT NOT NULL, created_at INTEGER, updated_at INTEGER, deleted_at INTEGER);
CREATE INDEX idx_rec_scan ON records(studio_id, collection, created_at DESC)
  WHERE deleted_at IS NULL;
-- expression indexes created at install from the manifest's storage.collections
-- CREATE INDEX idx_rec_h3_seed ON records(json_extract(doc,'$.seed')) WHERE studio_id='h3-studio';

-- media index. Bytes are in directories; these are pointers plus facts.
CREATE TABLE assets (
  id TEXT PRIMARY KEY,
  sha256 TEXT NOT NULL UNIQUE,        -- dedup is a constraint, not an algorithm
  kind TEXT NOT NULL CHECK (kind IN ('image','video','audio','other')),
  mime TEXT NOT NULL, bytes INTEGER NOT NULL,
  width INTEGER, height INTEGER, duration_s REAL, fps REAL,
  blob_path TEXT NOT NULL,              -- relative to the assets root, never absolute
  library_path TEXT,                    -- the human-readable hardlink
  origin_studio TEXT, pinned INTEGER NOT NULL DEFAULT 0,
  state TEXT NOT NULL DEFAULT 'ready',  -- ready | missing | corrupt
  created_at INTEGER, last_used_at INTEGER);

CREATE TABLE derived (
  asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  variant TEXT NOT NULL,                -- thumb-320 | poster | waveform-800 | proxy-h264
  path TEXT NOT NULL, bytes INTEGER NOT NULL,
  PRIMARY KEY (asset_id, variant)) WITHOUT ROWID;

-- the gallery
CREATE TABLE items (
  id TEXT PRIMARY KEY, studio_id TEXT NOT NULL,
  session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  kind TEXT NOT NULL,
  asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
  timeline_id TEXT REFERENCES timelines(id),   -- set when this item is an export
  title TEXT, params TEXT NOT NULL DEFAULT '{}',
  starred INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL, deleted_at INTEGER);
CREATE INDEX idx_items_feed   ON items(created_at DESC)            WHERE deleted_at IS NULL;
CREATE INDEX idx_items_studio ON items(studio_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_items_asset  ON items(asset_id);

-- provenance edges: the reason a central store exists
CREATE TABLE item_inputs (
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE RESTRICT,
  role TEXT NOT NULL,                   -- first_frame | last_frame | reference | audio_bed | clip
  PRIMARY KEY (item_id, asset_id, role)) WITHOUT ROWID;
CREATE INDEX idx_inputs_asset ON item_inputs(asset_id);

CREATE TABLE tags (
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  tag TEXT NOT NULL, PRIMARY KEY (item_id, tag)) WITHOUT ROWID;
CREATE VIRTUAL TABLE items_fts USING fts5(title, prompt, content='', tokenize='porter unicode61');

-- sequences: framework-owned, edited by the launcher or by helm-timeline
CREATE TABLE timelines (
  id TEXT PRIMARY KEY, name TEXT NOT NULL,
  target TEXT NOT NULL,                  -- {width,height,fps,sample_rate}
  tracks TEXT NOT NULL,                  -- clips reference asset ids; never copies
  revision INTEGER NOT NULL DEFAULT 1,  -- optimistic concurrency + undo
  created_at INTEGER, updated_at INTEGER);

CREATE TABLE inbox (
  id TEXT PRIMARY KEY, to_studio TEXT NOT NULL, from_studio TEXT NOT NULL,
  item_id TEXT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  role TEXT, created_at INTEGER, consumed_at INTEGER);
CREATE INDEX idx_inbox_pending ON inbox(to_studio, created_at) WHERE consumed_at IS NULL;
