-- Migration 4: what the platform API needs (M4). The DDL is docs/design/02-data-model.md §4
-- ("Studio-reported jobs") and §5 ("Schema v4 platform changes"); the reasons are in
-- docs/decisions.md, "2026-09-15 · M4 API and SDK". Do not edit this file once shipped.
--
-- Runs with foreign-key enforcement off (see migrate.go, apply), so jobs and log_files are
-- rebuilt by SQLite's create-copy-drop-rename procedure without firing step_runs' actions.

-- per-launch studio tokens (Q6): only the hash is stored
CREATE TABLE studio_tokens (
  token_sha256 TEXT PRIMARY KEY,
  studio_id TEXT NOT NULL,
  group_run_id TEXT,
  capabilities TEXT NOT NULL,
  created_at INTEGER NOT NULL, revoked_at INTEGER);
CREATE INDEX idx_tokens_group ON studio_tokens(group_run_id) WHERE revoked_at IS NULL;

-- which studios adopted or uploaded an asset (Q9): an access grant, not a reclaim reference
CREATE TABLE studio_assets (
  studio_id TEXT NOT NULL,
  asset_id TEXT NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (studio_id, asset_id)) WITHOUT ROWID;
CREATE INDEX idx_studio_assets_asset ON studio_assets(asset_id);

-- records gain an etag (Q18); every existing row gets a fresh one (first review #13)
ALTER TABLE records ADD COLUMN etag TEXT NOT NULL DEFAULT '';
UPDATE records SET etag = lower(hex(randomblob(16)));

-- an asset is reclaimable only once something has referenced it (first review #3)
ALTER TABLE assets ADD COLUMN first_referenced_at INTEGER;
UPDATE assets SET first_referenced_at = COALESCE(created_at, 0)
 WHERE EXISTS (SELECT 1 FROM items i WHERE i.asset_id = assets.id)
    OR EXISTS (SELECT 1 FROM item_inputs x WHERE x.asset_id = assets.id);

-- items_fts keyed by item_id, prompt taken from params.prompt (Q17)
DROP TABLE items_fts;
CREATE VIRTUAL TABLE items_fts USING fts5(item_id UNINDEXED, title, prompt, tokenize='porter unicode61');
INSERT INTO items_fts(item_id, title, prompt)
  SELECT id, COALESCE(title, ''), COALESCE(json_extract(params, '$.prompt'), '') FROM items WHERE deleted_at IS NULL;

-- jobs: 'task' kind and cancel_requested_at (Q24)
CREATE TABLE jobs_v4 (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('install','build','download','update','export','uninstall','task')),
  studio_id TEXT,
  state TEXT NOT NULL CHECK (state IN ('queued','running','succeeded','failed','cancelled','interrupted')),
  subject_kind TEXT, subject_id TEXT,
  progress_num INTEGER, progress_den INTEGER,
  last_error TEXT,
  created_at INTEGER NOT NULL, started_at INTEGER, finished_at INTEGER,
  cancel_requested_at INTEGER);
INSERT INTO jobs_v4 (id, kind, studio_id, state, subject_kind, subject_id, progress_num, progress_den, last_error, created_at, started_at, finished_at)
  SELECT id, kind, studio_id, state, subject_kind, subject_id, progress_num, progress_den, last_error, created_at, started_at, finished_at FROM jobs;
DROP TABLE jobs;
ALTER TABLE jobs_v4 RENAME TO jobs;
CREATE INDEX idx_jobs_studio ON jobs(studio_id, created_at DESC);
CREATE INDEX idx_jobs_live ON jobs(state) WHERE state IN ('queued','running');

-- log_files: a task job's log (Q24)
CREATE TABLE log_files_v4 (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL CHECK (kind IN ('run','build','task')),
  owner_kind TEXT NOT NULL CHECK (owner_kind IN ('process','step_run','job')),
  owner_id TEXT NOT NULL,
  studio_id TEXT NOT NULL,
  truncated INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL);
INSERT INTO log_files_v4 SELECT id, path, kind, owner_kind, owner_id, studio_id, truncated, created_at FROM log_files;
DROP TABLE log_files;
ALTER TABLE log_files_v4 RENAME TO log_files;
CREATE INDEX idx_logs_studio ON log_files(studio_id, created_at DESC);
