-- Migration 5: the launcher's settings (M6). The DDL is docs/design/02-data-model.md §5
-- ("Schema v5"); the reason is in docs/decisions.md, "2026-09-16 · M6 design and UI", Q8.
-- Do not edit this file once shipped.

-- one row per setting the user changed; an absent key means the default
CREATE TABLE settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at INTEGER NOT NULL) WITHOUT ROWID;
