-- Migration 6: the timeline document, its revisions, and an export's process (M8).
-- The DDL is docs/design/02-data-model.md §5 ("Schema v6 timeline changes"); the
-- reasons are in docs/decisions.md, "2026-09-16 · M8 timeline and export", Q10-Q17.
-- Do not edit this file once shipped.

-- A sequence is owned by the studio that made it, or by the launcher (NULL).
-- Deleting one is a soft delete: an exported item still names it, and its clips
-- stop holding their footage against reclaim.
ALTER TABLE timelines ADD COLUMN studio_id TEXT;
ALTER TABLE timelines ADD COLUMN deleted_at INTEGER;
CREATE INDEX idx_timelines_studio ON timelines(studio_id, updated_at DESC) WHERE deleted_at IS NULL;

-- Every document a write replaced. Undo is the previous revision (05 §6),
-- written forward rather than rewound, so undoing loses nothing.
CREATE TABLE timeline_revisions (
  timeline_id TEXT NOT NULL REFERENCES timelines(id) ON DELETE CASCADE,
  revision INTEGER NOT NULL,
  name TEXT NOT NULL,
  target TEXT NOT NULL,
  tracks TEXT NOT NULL,
  saved_at INTEGER NOT NULL,
  PRIMARY KEY (timeline_id, revision)) WITHOUT ROWID;

-- An export's ffmpeg: its identity, verified before anything is ever signalled,
-- and the partial file to remove when it is stopped (M3 review #1's rule, for
-- exports).
ALTER TABLE jobs ADD COLUMN pid INTEGER;
ALTER TABLE jobs ADD COLUMN pid_start_time INTEGER;
ALTER TABLE jobs ADD COLUMN pgid INTEGER;
ALTER TABLE jobs ADD COLUMN work_path TEXT;
CREATE INDEX idx_jobs_subject ON jobs(subject_kind, subject_id, created_at DESC);

-- log_files.kind gains 'export', which needs the table rebuilt.
CREATE TABLE log_files_v6 (
  id TEXT PRIMARY KEY,
  path TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL CHECK (kind IN ('run','build','task','export')),
  owner_kind TEXT NOT NULL CHECK (owner_kind IN ('process','step_run','job')),
  owner_id TEXT NOT NULL,
  studio_id TEXT NOT NULL,
  truncated INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL);
INSERT INTO log_files_v6 SELECT id, path, kind, owner_kind, owner_id, studio_id, truncated, created_at FROM log_files;
DROP TABLE log_files;
ALTER TABLE log_files_v6 RENAME TO log_files;
CREATE INDEX idx_logs_studio ON log_files(studio_id, created_at DESC);
