-- Migration 7: what the user approved, and which checkpoint they chose (M7).
-- The DDL is docs/design/02-data-model.md §5 ("Schema v7 approval and
-- selection"); the reasons are in docs/decisions.md, "2026-09-16 · M7 library,
-- editor and iris", Q10, Q20 and Q21.
-- Do not edit this file once shipped.

-- What the user last approved for this studio, and when. The digest covers
-- everything that executes and where it comes from, so an install, a retry or
-- a launch whose freshly computed digest differs is refused until the preview
-- has been shown again — which is what makes an Override that edits a command
-- show the change instead of running it.
--
-- NULL means never approved, which every studio installed before v7 is: each
-- asks once, at its next launch. approved_commit is what install checks out,
-- so a branch that moved after the screen was shown still builds what was
-- agreed to.
ALTER TABLE installations ADD COLUMN approved_digest TEXT;
ALTER TABLE installations ADD COLUMN approved_commit TEXT;
ALTER TABLE installations ADD COLUMN approved_at INTEGER;

-- At most one selectable weight per studio is the chosen one. The index is
-- what enforces it, rather than a check in Go that two writers could interleave
-- around; `selected` already exists and already defaults to 0, so only the
-- constraint is new.
CREATE UNIQUE INDEX idx_bind_selected ON studio_model_bindings(studio_id)
  WHERE selected = 1;
