"""helmstudio's runtime SDK for Python: a client for the platform API.

    from helm_runtime_sdk import from_env
    helm = from_env()
    asset = helm.assets.adopt({"path": out, "kind": "video"})
    helm.gallery.add({"kind": "video", "asset_id": asset["id"], "params": {"seed": 42}})

Standard library only. Method names match the Go and Node clients
(docs/design/04-packages.md §4). _generated.py is generated by api/gen; the rest
is written by hand. Sync only for now; the embedded provider for Python is
decided with the Python studios (docs/decisions.md M4 Q3, Q25).
"""

import os

from ._generated import API_VERSION, Client
from ._transport import Event, HelmError, RawResponse, Transport

__all__ = ["API_VERSION", "Client", "Event", "HelmError", "RawResponse", "Transport", "from_env", "remote"]


def remote(base: str, token: str) -> Client:
    """A client for the API at base, e.g. http://127.0.0.1:8700/api/v1."""
    return Client(Transport(base, token))


def from_env() -> Client:
    """The remote client when HELM_API is set, as helmstudio and helm dev do."""
    api = os.environ.get("HELM_API")
    if not api:
        raise HelmError(0, "no_provider", "HELM_API is not set; run under helmstudio or helm dev")
    token = os.environ.get("HELM_TOKEN")
    if not token:
        raise HelmError(0, "no_token", "HELM_API is set but HELM_TOKEN is not; a studio with no capabilities gets no token")
    return remote(api, token)
