# Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.
"""Generated groups of the helmstudio runtime SDK. Import from helm_runtime_sdk."""

from typing import Any, Dict, Optional, Sequence

from ._transport import Transport, quote

API_VERSION = "1.0.0"


class MeGroup:
    """The me group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def get(self) -> Any:
        """Who the token belongs to, what it may do, and how much quota is left. (GET /me)"""
        return self._t.request("GET", "/me", query={}, headers={}, expect="json")

class EventsGroup:
    """The events group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def subscribe(self, *, last_event_id: Optional[Any] = None) -> Any:
        """Server-sent events for the calling studio. (GET /events)"""
        return self._t.request("GET", "/events", query={}, headers={"Last-Event-ID": last_event_id}, expect="sse")

class KVGroup:
    """The kv group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, ns: str, *, prefix: Optional[Any] = None, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """List keys in a namespace, with sizes and modified times. No values. (GET /kv/{ns})"""
        return self._t.request("GET", "/kv/" + quote(ns), query={"prefix": prefix, "limit": limit, "cursor": cursor}, headers={}, expect="json")

    def get(self, ns: str, key: str) -> Any:
        """Read one document. (GET /kv/{ns}/{key})"""
        return self._t.request("GET", "/kv/" + quote(ns) + "/" + quote(key), query={}, headers={}, expect="json")

    def put(self, ns: str, key: str, body: Dict[str, Any], *, if_match: Optional[Any] = None) -> Any:
        """Create or replace a document. (PUT /kv/{ns}/{key})"""
        return self._t.request("PUT", "/kv/" + quote(ns) + "/" + quote(key), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/json")

    def patch(self, ns: str, key: str, body: Dict[str, Any], *, if_match: Optional[Any] = None) -> Any:
        """Apply a JSON merge patch (RFC 7396) to an existing document. (PATCH /kv/{ns}/{key})"""
        return self._t.request("PATCH", "/kv/" + quote(ns) + "/" + quote(key), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def delete(self, ns: str, key: str, *, if_match: Optional[Any] = None) -> Any:
        """Remove a document. (DELETE /kv/{ns}/{key})"""
        return self._t.request("DELETE", "/kv/" + quote(ns) + "/" + quote(key), query={}, headers={"If-Match": if_match}, expect="empty")

class SessionsGroup:
    """The sessions group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """The calling studio's sessions, most recently opened first. (GET /sessions)"""
        return self._t.request("GET", "/sessions", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def create(self, body: Dict[str, Any]) -> Any:
        """Create a session. (POST /sessions)"""
        return self._t.request("POST", "/sessions", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def get(self, id: str) -> Any:
        """One session. A deleted session, or another studio's, is 404. (GET /sessions/{id})"""
        return self._t.request("GET", "/sessions/" + quote(id), query={}, headers={}, expect="json")

    def update(self, id: str, body: Dict[str, Any], *, if_match: Optional[Any] = None) -> Any:
        """Rename, or merge changes into the state document. (PATCH /sessions/{id})"""
        return self._t.request("PATCH", "/sessions/" + quote(id), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def delete(self, id: str, *, if_match: Optional[Any] = None) -> Any:
        """Soft-delete. Its name becomes free; items keep their session_id. (DELETE /sessions/{id})"""
        return self._t.request("DELETE", "/sessions/" + quote(id), query={}, headers={"If-Match": if_match}, expect="empty")

    def duplicate(self, id: str, body: Dict[str, Any]) -> Any:
        """Copy a session's state under a new name. The copy has never been opened. (POST /sessions/{id}:duplicate)"""
        return self._t.request("POST", "/sessions/" + quote(id) + ":duplicate", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def activate(self, id: str) -> Any:
        """Set opened_at to now. Changes neither the state nor the etag, nor any process. (POST /sessions/{id}:activate)"""
        return self._t.request("POST", "/sessions/" + quote(id) + ":activate", query={}, headers={}, expect="empty")

class RecordsGroup:
    """The records group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def query(self, collection: str, *, where: Optional[Sequence[str]] = None, order: Optional[Any] = None, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """Query a collection with the closed filter language. Never SQL. (GET /records/{collection})"""
        return self._t.request("GET", "/records/" + quote(collection), query={"where": where, "order": order, "limit": limit, "cursor": cursor}, headers={}, expect="json")

    def insert(self, collection: str, body: Dict[str, Any]) -> Any:
        """Insert a document; returns its id and etag. (POST /records/{collection})"""
        return self._t.request("POST", "/records/" + quote(collection), query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def get(self, collection: str, id: str) -> Any:
        """One record. Deleted, in another collection, or another studio's is 404. (GET /records/{collection}/{id})"""
        return self._t.request("GET", "/records/" + quote(collection) + "/" + quote(id), query={}, headers={}, expect="json")

    def replace(self, collection: str, id: str, body: Dict[str, Any], *, if_match: Optional[Any] = None) -> Any:
        """Replace a document. If-Match on the etag; 409 on conflict. (PUT /records/{collection}/{id})"""
        return self._t.request("PUT", "/records/" + quote(collection) + "/" + quote(id), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/json")

    def patch(self, collection: str, id: str, body: Dict[str, Any], *, if_match: Optional[Any] = None) -> Any:
        """Apply a JSON merge patch (RFC 7396). If-Match on the etag; 409 on conflict. (PATCH /records/{collection}/{id})"""
        return self._t.request("PATCH", "/records/" + quote(collection) + "/" + quote(id), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def delete(self, collection: str, id: str, *, if_match: Optional[Any] = None) -> Any:
        """Soft-delete, so an undo is possible and a sync never sees a gap. (DELETE /records/{collection}/{id})"""
        return self._t.request("DELETE", "/records/" + quote(collection) + "/" + quote(id), query={}, headers={"If-Match": if_match}, expect="empty")

class AssetsGroup:
    """The assets group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def upload(self, body: bytes, content_type: str, *, kind: Any, filename: Optional[Any] = None, pinned: Optional[Any] = None, width: Optional[Any] = None, height: Optional[Any] = None, duration_s: Optional[Any] = None, fps: Optional[Any] = None) -> Any:
        """Upload bytes. Idempotent on content. (POST /assets)"""
        return self._t.request("POST", "/assets", query={"kind": kind, "filename": filename, "pinned": pinned, "width": width, "height": height, "duration_s": duration_s, "fps": fps}, headers={}, expect="json", raw_body=body, content_type=content_type)

    def adopt(self, body: Dict[str, Any]) -> Any:
        """Adopt a file from the stage or data directory by hardlink — no copy, no HTTP body. (POST /assets:adopt)"""
        return self._t.request("POST", "/assets:adopt", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def read(self, id: str, *, range: Optional[Any] = None) -> Any:
        """The asset's bytes, with Range. (GET /assets/{id})"""
        return self._t.request("GET", "/assets/" + quote(id), query={}, headers={"Range": range}, expect="raw")

    def thumb(self, id: str, *, w: Optional[Any] = None) -> Any:
        """A thumbnail, generated once and cached. (GET /assets/{id}/thumb)"""
        return self._t.request("GET", "/assets/" + quote(id) + "/thumb", query={"w": w}, headers={}, expect="raw")

    def lineage(self, id: str, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """Downstream provenance — every item ever made from this asset, recursively. (GET /assets/{id}/lineage)"""
        return self._t.request("GET", "/assets/" + quote(id) + "/lineage", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

class GalleryGroup:
    """The gallery group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def add(self, body: Dict[str, Any]) -> Any:
        """Record an output with its params, inputs, tags and session. One call per generation. (POST /gallery/items)"""
        return self._t.request("POST", "/gallery/items", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def query(self, *, scope: Optional[Any] = None, studio: Optional[Any] = None, kind: Optional[Any] = None, tag: Optional[Sequence[str]] = None, session_id: Optional[Any] = None, starred: Optional[Any] = None, asset_id: Optional[Any] = None, since: Optional[Any] = None, until: Optional[Any] = None, q: Optional[Any] = None, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """Query items, scoped to the caller unless scope=all. (GET /gallery/items)"""
        return self._t.request("GET", "/gallery/items", query={"scope": scope, "studio": studio, "kind": kind, "tag": tag, "session_id": session_id, "starred": starred, "asset_id": asset_id, "since": since, "until": until, "q": q, "limit": limit, "cursor": cursor}, headers={}, expect="json")

    def get(self, id: str) -> Any:
        """One item. Another studio's without gallery.read_all, or a deleted one, is 404. (GET /gallery/items/{id})"""
        return self._t.request("GET", "/gallery/items/" + quote(id), query={}, headers={}, expect="json")

    def update(self, id: str, body: Dict[str, Any]) -> Any:
        """Star, tag or rename one of the caller's own items. (PATCH /gallery/items/{id})"""
        return self._t.request("PATCH", "/gallery/items/" + quote(id), query={}, headers={}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def delete(self, id: str) -> Any:
        """Soft-delete one of the caller's own items. (DELETE /gallery/items/{id})"""
        return self._t.request("DELETE", "/gallery/items/" + quote(id), query={}, headers={}, expect="empty")

    def lineage(self, id: str, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """Upstream provenance — the items whose outputs this item was made from, recursively. (GET /gallery/items/{id}/lineage)"""
        return self._t.request("GET", "/gallery/items/" + quote(id) + "/lineage", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

class HandoffGroup:
    """The handoff group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def send(self, body: Dict[str, Any]) -> Any:
        """Put an item in another studio's inbox. (POST /handoff)"""
        return self._t.request("POST", "/handoff", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

class InboxGroup:
    """The inbox group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """Handoffs to the caller not yet consumed, oldest first. (GET /inbox)"""
        return self._t.request("GET", "/inbox", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def consume(self, id: str) -> Any:
        """Mark an entry handled. Idempotent. (POST /inbox/{id}:consume)"""
        return self._t.request("POST", "/inbox/" + quote(id) + ":consume", query={}, headers={}, expect="empty")

class JobsGroup:
    """The jobs group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def list(self, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """The calling studio's jobs, of every kind, newest first. (GET /jobs)"""
        return self._t.request("GET", "/jobs", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def create(self, body: Dict[str, Any]) -> Any:
        """Report a long-running piece of the studio's own work as a task job. (POST /jobs)"""
        return self._t.request("POST", "/jobs", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def get(self, id: str) -> Any:
        """One of the calling studio's jobs. Another studio's is 404. (GET /jobs/{id})"""
        return self._t.request("GET", "/jobs/" + quote(id), query={}, headers={}, expect="json")

    def update(self, id: str, body: Dict[str, Any]) -> Any:
        """Report progress on, or finish, a task job the calling studio created. (PATCH /jobs/{id})"""
        return self._t.request("PATCH", "/jobs/" + quote(id), query={}, headers={}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def cancel(self, id: str) -> Any:
        """Ask for one of the calling studio's task jobs to be cancelled. (POST /jobs/{id}:cancel)"""
        return self._t.request("POST", "/jobs/" + quote(id) + ":cancel", query={}, headers={}, expect="empty")

    def logs(self, id: str) -> Any:
        """One of the calling studio's job logs as server-sent events, from the start, then live until the job finishes. (GET /jobs/{id}/logs)"""
        return self._t.request("GET", "/jobs/" + quote(id) + "/logs", query={}, headers={}, expect="sse")

    def append_log(self, id: str, body: Dict[str, Any]) -> Any:
        """Append lines to a running task job's log. (POST /jobs/{id}/logs)"""
        return self._t.request("POST", "/jobs/" + quote(id) + "/logs", query={}, headers={}, expect="empty", json_body=body, content_type="application/json")

class TimelineGroup:
    """The timeline group."""

    def __init__(self, transport: Transport) -> None:
        self._t = transport

    def create(self, body: Dict[str, Any]) -> Any:
        """Create a sequence from clips, or from whole tracks. (POST /timeline)"""
        return self._t.request("POST", "/timeline", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def list(self, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """The sequences the caller may read, newest first. (GET /timeline)"""
        return self._t.request("GET", "/timeline", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def get(self, id: str) -> Any:
        """One sequence. One the caller may not read is 404. (GET /timeline/{id})"""
        return self._t.request("GET", "/timeline/" + quote(id), query={}, headers={}, expect="json")

    def update(self, id: str, body: Dict[str, Any], *, if_match: Any) -> Any:
        """Edit a sequence. Every edit is a revision. (PATCH /timeline/{id})"""
        return self._t.request("PATCH", "/timeline/" + quote(id), query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/merge-patch+json")

    def delete(self, id: str, *, if_match: Optional[Any] = None) -> Any:
        """Delete a sequence. Its exports and their lineage stay. (DELETE /timeline/{id})"""
        return self._t.request("DELETE", "/timeline/" + quote(id), query={}, headers={"If-Match": if_match}, expect="empty")

    def revisions(self, id: str, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """The sequence's earlier revisions, newest first. (GET /timeline/{id}/revisions)"""
        return self._t.request("GET", "/timeline/" + quote(id) + "/revisions", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def revert(self, id: str, body: Dict[str, Any], *, if_match: Any) -> Any:
        """Write an earlier revision back as the newest one. (POST /timeline/{id}:revert)"""
        return self._t.request("POST", "/timeline/" + quote(id) + ":revert", query={}, headers={"If-Match": if_match}, expect="json", json_body=body, content_type="application/json")

    def append(self, body: Dict[str, Any]) -> Any:
        """Add one asset to the end of a track, without stealing focus. (POST /timeline:append)"""
        return self._t.request("POST", "/timeline:append", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def open(self, id: str) -> Any:
        """Ask the framework to show its editor on this sequence. (POST /timeline/{id}:open)"""
        return self._t.request("POST", "/timeline/" + quote(id) + ":open", query={}, headers={}, expect="json")

    def plan(self, id: str, *, preset: Optional[Any] = None) -> Any:
        """Which path an export would take, and why. (GET /timeline/{id}:plan)"""
        return self._t.request("GET", "/timeline/" + quote(id) + ":plan", query={"preset": preset}, headers={}, expect="json")

    def export(self, id: str, body: Dict[str, Any]) -> Any:
        """Export the sequence. Answers with the job that renders it. (POST /timeline/{id}:export)"""
        return self._t.request("POST", "/timeline/" + quote(id) + ":export", query={}, headers={}, expect="json", json_body=body, content_type="application/json")

    def exports(self, id: str, *, limit: Optional[Any] = None, cursor: Optional[Any] = None) -> Any:
        """The sequence's export jobs, newest first. (GET /timeline/{id}/exports)"""
        return self._t.request("GET", "/timeline/" + quote(id) + "/exports", query={"limit": limit, "cursor": cursor}, headers={}, expect="json")

    def cancel_export(self, id: str, job: str) -> Any:
        """Stop a running export and leave nothing behind. (POST /timeline/{id}/exports/{job}:cancel)"""
        return self._t.request("POST", "/timeline/" + quote(id) + "/exports/" + quote(job) + ":cancel", query={}, headers={}, expect="empty")


class Client:
    """One attribute per API group, the same names as the Go and Node clients."""

    def __init__(self, transport: Transport) -> None:
        self.me = MeGroup(transport)
        self.events = EventsGroup(transport)
        self.kv = KVGroup(transport)
        self.sessions = SessionsGroup(transport)
        self.records = RecordsGroup(transport)
        self.assets = AssetsGroup(transport)
        self.gallery = GalleryGroup(transport)
        self.handoff = HandoffGroup(transport)
        self.inbox = InboxGroup(transport)
        self.jobs = JobsGroup(transport)
        self.timeline = TimelineGroup(transport)
