// Package helm is helmstudio's runtime SDK for Go: a typed client for the
// platform API in api/openapi.yaml — kv, sessions, records, assets, gallery,
// handoff, inbox, jobs, events and /me — with provider selection
// (docs/design/04-packages.md §4).
//
// It uses the standard library only. The embedded provider, which needs
// SQLite, is a separate module: import
// github.com/janishar/helmstudio/packages/helm-runtime-sdk/go/embedded for its
// side effect and FromEnv will use it when HELM_API is not set.
//
//	c, err := helm.FromEnv()
//	asset, err := c.Assets.Adopt(ctx, helm.AdoptRequest{Path: out, Kind: helm.AssetKindVideo})
//	item, err := c.Gallery.Add(ctx, helm.ItemCreate{Kind: helm.AssetKindVideo, AssetID: asset.ID,
//		Params: map[string]any{"seed": 42}, Inputs: []helm.ItemInput{{AssetID: frame, Role: "first_frame"}}})
//
// zz_types.go and zz_client.go are generated by api/gen; everything else here
// is written by hand.
package helm

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"strings"
	"sync"
)

// Environment variables the daemon and helm dev inject at spawn
// (docs/design/07-platform-services.md §3).
const (
	EnvAPI      = "HELM_API"
	EnvToken    = "HELM_TOKEN"
	EnvStudioID = "HELM_STUDIO_ID"
	EnvStageDir = "HELM_STAGE_DIR"
)

// Option configures a remote client.
type Option func(*transport)

// WithHTTPClient sets the HTTP client requests go through. The embedded
// provider uses it to serve requests in process.
func WithHTTPClient(c *http.Client) Option {
	return func(t *transport) { t.http = c }
}

// NewRemote returns a client for the API at base (for example
// http://127.0.0.1:8700/api/v1), authenticating with token.
func NewRemote(base, token string, opts ...Option) *Client {
	t := &transport{base: strings.TrimRight(base, "/"), token: token, http: http.DefaultClient}
	for _, o := range opts {
		o(t)
	}
	return newClient(t)
}

var (
	embeddedMu sync.Mutex
	embedded   func() (*Client, error)
)

// RegisterEmbedded is called by the embedded provider's package when it is
// imported. Studios never call it.
func RegisterEmbedded(open func() (*Client, error)) {
	embeddedMu.Lock()
	defer embeddedMu.Unlock()
	embedded = open
}

// ErrNoProvider means FromEnv found no HELM_API and no embedded provider.
var ErrNoProvider = errors.New("helm: HELM_API is not set and no embedded provider is imported; run under helmstudio or helm dev, or import github.com/janishar/helmstudio/packages/helm-runtime-sdk/go/embedded")

// FromEnv returns the remote client when HELM_API is set, and the embedded
// provider otherwise (docs/design/04-packages.md §4, "Provider selection").
func FromEnv() (*Client, error) {
	if api := os.Getenv(EnvAPI); api != "" {
		tok := os.Getenv(EnvToken)
		if tok == "" {
			return nil, fmt.Errorf("helm: %s is set but %s is not; a studio with no capabilities gets no token", EnvAPI, EnvToken)
		}
		return NewRemote(api, tok), nil
	}
	embeddedMu.Lock()
	open := embedded
	embeddedMu.Unlock()
	if open == nil {
		return nil, ErrNoProvider
	}
	return open()
}
