// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.

package helm

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"time"
)

var (
	_ = io.EOF
	_ = strconv.Itoa
	_ = time.RFC3339
)

// Client is the runtime SDK: one field per API group, the same names in Go,
// Python and Node (docs/design/04-packages.md §4). Every provider fills the same
// interfaces.
type Client struct {
	Me       MeAPI
	Events   EventsAPI
	KV       KVAPI
	Sessions SessionsAPI
	Records  RecordsAPI
	Assets   AssetsAPI
	Gallery  GalleryAPI
	Handoff  HandoffAPI
	Inbox    InboxAPI
	Jobs     JobsAPI
}

// MeAPI is the me group.
type MeAPI interface {
	// Get: Who the token belongs to, what it may do, and how much quota is left. (GET /me)
	Get(ctx context.Context) (*Me, error)
}

// EventsAPI is the events group.
type EventsAPI interface {
	// Subscribe: Server-sent events for the calling studio. (GET /events)
	Subscribe(ctx context.Context, params *EventsSubscribeParams) (*EventStream, error)
}

// KVAPI is the kv group.
type KVAPI interface {
	// List: List keys in a namespace, with sizes and modified times. No values. (GET
	// /kv/{ns})
	List(ctx context.Context, ns string, params *KVListParams) (*KVKeyPage, error)
	// Get: Read one document. (GET /kv/{ns}/{key})
	Get(ctx context.Context, ns string, key string) (*KVDoc, error)
	// Put: Create or replace a document. (PUT /kv/{ns}/{key})
	Put(ctx context.Context, ns string, key string, body map[string]any, params *KVPutParams) (*KVDoc, error)
	// Patch: Apply a JSON merge patch (RFC 7396) to an existing document. (PATCH
	// /kv/{ns}/{key})
	Patch(ctx context.Context, ns string, key string, body map[string]any, params *KVPatchParams) (*KVDoc, error)
	// Delete: Remove a document. (DELETE /kv/{ns}/{key})
	Delete(ctx context.Context, ns string, key string, params *KVDeleteParams) error
}

// SessionsAPI is the sessions group.
type SessionsAPI interface {
	// List: The calling studio's sessions, most recently opened first. (GET /sessions)
	List(ctx context.Context, params *SessionsListParams) (*SessionPage, error)
	// Create: Create a session. (POST /sessions)
	Create(ctx context.Context, body SessionCreate) (*Session, error)
	// Get: One session. A deleted session, or another studio's, is 404. (GET
	// /sessions/{id})
	Get(ctx context.Context, id string) (*Session, error)
	// Update: Rename, or merge changes into the state document. (PATCH /sessions/{id})
	Update(ctx context.Context, id string, body map[string]any, params *SessionsUpdateParams) (*Session, error)
	// Delete: Soft-delete. Its name becomes free; items keep their session_id. (DELETE
	// /sessions/{id})
	Delete(ctx context.Context, id string, params *SessionsDeleteParams) error
	// Duplicate: Copy a session's state under a new name. The copy has never been opened.
	// (POST /sessions/{id}:duplicate)
	Duplicate(ctx context.Context, id string, body SessionDuplicate) (*Session, error)
	// Activate: Set opened_at to now. Changes neither the state nor the etag, nor any
	// process. (POST /sessions/{id}:activate)
	Activate(ctx context.Context, id string) error
}

// RecordsAPI is the records group.
type RecordsAPI interface {
	// Query: Query a collection with the closed filter language. Never SQL. (GET
	// /records/{collection})
	Query(ctx context.Context, collection string, params *RecordsQueryParams) (*RecordPage, error)
	// Insert: Insert a document; returns its id and etag. (POST /records/{collection})
	Insert(ctx context.Context, collection string, body map[string]any) (*Record, error)
	// Get: One record. Deleted, in another collection, or another studio's is 404. (GET
	// /records/{collection}/{id})
	Get(ctx context.Context, collection string, id string) (*Record, error)
	// Replace: Replace a document. If-Match on the etag; 409 on conflict. (PUT
	// /records/{collection}/{id})
	Replace(ctx context.Context, collection string, id string, body map[string]any, params *RecordsReplaceParams) (*Record, error)
	// Patch: Apply a JSON merge patch (RFC 7396). If-Match on the etag; 409 on conflict.
	// (PATCH /records/{collection}/{id})
	Patch(ctx context.Context, collection string, id string, body map[string]any, params *RecordsPatchParams) (*Record, error)
	// Delete: Soft-delete, so an undo is possible and a sync never sees a gap. (DELETE
	// /records/{collection}/{id})
	Delete(ctx context.Context, collection string, id string, params *RecordsDeleteParams) error
}

// AssetsAPI is the assets group.
type AssetsAPI interface {
	// Upload: Upload bytes. Idempotent on content. (POST /assets)
	Upload(ctx context.Context, body io.Reader, contentType string, params *AssetsUploadParams) (*Asset, error)
	// Adopt: Adopt a file from the stage or data directory by hardlink — no copy, no
	// HTTP body. (POST /assets:adopt)
	Adopt(ctx context.Context, body AdoptRequest) (*Asset, error)
	// Read: The asset's bytes, with Range. (GET /assets/{id})
	Read(ctx context.Context, id string, params *AssetsReadParams) (*RawResponse, error)
	// Thumb: A thumbnail, generated once and cached. (GET /assets/{id}/thumb)
	Thumb(ctx context.Context, id string, params *AssetsThumbParams) (*RawResponse, error)
	// Lineage: Downstream provenance — every item ever made from this asset,
	// recursively. (GET /assets/{id}/lineage)
	Lineage(ctx context.Context, id string, params *AssetsLineageParams) (*ItemPage, error)
}

// GalleryAPI is the gallery group.
type GalleryAPI interface {
	// Add: Record an output with its params, inputs, tags and session. One call per
	// generation. (POST /gallery/items)
	Add(ctx context.Context, body ItemCreate) (*Item, error)
	// Query: Query items, scoped to the caller unless scope=all. (GET /gallery/items)
	Query(ctx context.Context, params *GalleryQueryParams) (*ItemPage, error)
	// Get: One item. Another studio's without gallery.read_all, or a deleted one, is 404.
	// (GET /gallery/items/{id})
	Get(ctx context.Context, id string) (*Item, error)
	// Update: Star, tag or rename one of the caller's own items. (PATCH
	// /gallery/items/{id})
	Update(ctx context.Context, id string, body map[string]any) (*Item, error)
	// Delete: Soft-delete one of the caller's own items. (DELETE /gallery/items/{id})
	Delete(ctx context.Context, id string) error
	// Lineage: Upstream provenance — the items whose outputs this item was made from,
	// recursively. (GET /gallery/items/{id}/lineage)
	Lineage(ctx context.Context, id string, params *GalleryLineageParams) (*ItemPage, error)
}

// HandoffAPI is the handoff group.
type HandoffAPI interface {
	// Send: Put an item in another studio's inbox. (POST /handoff)
	Send(ctx context.Context, body HandoffRequest) (*Handoff, error)
}

// InboxAPI is the inbox group.
type InboxAPI interface {
	// List: Handoffs to the caller not yet consumed, oldest first. (GET /inbox)
	List(ctx context.Context, params *InboxListParams) (*InboxPage, error)
	// Consume: Mark an entry handled. Idempotent. (POST /inbox/{id}:consume)
	Consume(ctx context.Context, id string) error
}

// JobsAPI is the jobs group.
type JobsAPI interface {
	// List: The calling studio's jobs, of every kind, newest first. (GET /jobs)
	List(ctx context.Context, params *JobsListParams) (*JobPage, error)
	// Create: Report a long-running piece of the studio's own work as a task job. (POST
	// /jobs)
	Create(ctx context.Context, body TaskCreate) (*Job, error)
	// Get: One of the calling studio's jobs. Another studio's is 404. (GET /jobs/{id})
	Get(ctx context.Context, id string) (*Job, error)
	// Update: Report progress on, or finish, a task job the calling studio created. (PATCH
	// /jobs/{id})
	Update(ctx context.Context, id string, body map[string]any) (*Job, error)
	// Cancel: Ask for one of the calling studio's task jobs to be cancelled. (POST
	// /jobs/{id}:cancel)
	Cancel(ctx context.Context, id string) error
	// Logs: One of the calling studio's job logs as server-sent events, from the start,
	// then live until the job finishes. (GET /jobs/{id}/logs)
	Logs(ctx context.Context, id string) (*EventStream, error)
	// AppendLog: Append lines to a running task job's log. (POST /jobs/{id}/logs)
	AppendLog(ctx context.Context, id string, body LogAppend) error
}

func newClient(t *transport) *Client {
	return &Client{
		Me:       meRemote{t},
		Events:   eventsRemote{t},
		KV:       kvRemote{t},
		Sessions: sessionsRemote{t},
		Records:  recordsRemote{t},
		Assets:   assetsRemote{t},
		Gallery:  galleryRemote{t},
		Handoff:  handoffRemote{t},
		Inbox:    inboxRemote{t},
		Jobs:     jobsRemote{t},
	}
}

type meRemote struct{ t *transport }

func (g meRemote) Get(ctx context.Context) (*Me, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/me", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Me](resp)
}

type eventsRemote struct{ t *transport }

func (g eventsRemote) Subscribe(ctx context.Context, params *EventsSubscribeParams) (*EventStream, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.LastEventID != nil {
			h.Set("Last-Event-ID", (*params.LastEventID))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/events", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return newEventStream(resp), nil
}

type kvRemote struct{ t *transport }

func (g kvRemote) List(ctx context.Context, ns string, params *KVListParams) (*KVKeyPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Prefix != nil {
			q.Add("prefix", (*params.Prefix))
		}
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/kv/"+url.PathEscape(ns), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[KVKeyPage](resp)
}

func (g kvRemote) Get(ctx context.Context, ns string, key string) (*KVDoc, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/kv/"+url.PathEscape(ns)+"/"+url.PathEscape(key), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[KVDoc](resp)
}

func (g kvRemote) Put(ctx context.Context, ns string, key string, body map[string]any, params *KVPutParams) (*KVDoc, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PUT", "/kv/"+url.PathEscape(ns)+"/"+url.PathEscape(key), q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[KVDoc](resp)
}

func (g kvRemote) Patch(ctx context.Context, ns string, key string, body map[string]any, params *KVPatchParams) (*KVDoc, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PATCH", "/kv/"+url.PathEscape(ns)+"/"+url.PathEscape(key), q, h, rd, "application/merge-patch+json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[KVDoc](resp)
}

func (g kvRemote) Delete(ctx context.Context, ns string, key string, params *KVDeleteParams) error {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	resp, err := g.t.do(ctx, "DELETE", "/kv/"+url.PathEscape(ns)+"/"+url.PathEscape(key), q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

type sessionsRemote struct{ t *transport }

func (g sessionsRemote) List(ctx context.Context, params *SessionsListParams) (*SessionPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/sessions", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[SessionPage](resp)
}

func (g sessionsRemote) Create(ctx context.Context, body SessionCreate) (*Session, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/sessions", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Session](resp)
}

func (g sessionsRemote) Get(ctx context.Context, id string) (*Session, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/sessions/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Session](resp)
}

func (g sessionsRemote) Update(ctx context.Context, id string, body map[string]any, params *SessionsUpdateParams) (*Session, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PATCH", "/sessions/"+url.PathEscape(id), q, h, rd, "application/merge-patch+json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Session](resp)
}

func (g sessionsRemote) Delete(ctx context.Context, id string, params *SessionsDeleteParams) error {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	resp, err := g.t.do(ctx, "DELETE", "/sessions/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

func (g sessionsRemote) Duplicate(ctx context.Context, id string, body SessionDuplicate) (*Session, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/sessions/"+url.PathEscape(id)+":duplicate", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Session](resp)
}

func (g sessionsRemote) Activate(ctx context.Context, id string) error {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "POST", "/sessions/"+url.PathEscape(id)+":activate", q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

type recordsRemote struct{ t *transport }

func (g recordsRemote) Query(ctx context.Context, collection string, params *RecordsQueryParams) (*RecordPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		for _, v := range params.Where {
			q.Add("where", v)
		}
		if params.Order != nil {
			q.Add("order", (*params.Order))
		}
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/records/"+url.PathEscape(collection), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[RecordPage](resp)
}

func (g recordsRemote) Insert(ctx context.Context, collection string, body map[string]any) (*Record, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/records/"+url.PathEscape(collection), q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Record](resp)
}

func (g recordsRemote) Get(ctx context.Context, collection string, id string) (*Record, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/records/"+url.PathEscape(collection)+"/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Record](resp)
}

func (g recordsRemote) Replace(ctx context.Context, collection string, id string, body map[string]any, params *RecordsReplaceParams) (*Record, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PUT", "/records/"+url.PathEscape(collection)+"/"+url.PathEscape(id), q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Record](resp)
}

func (g recordsRemote) Patch(ctx context.Context, collection string, id string, body map[string]any, params *RecordsPatchParams) (*Record, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PATCH", "/records/"+url.PathEscape(collection)+"/"+url.PathEscape(id), q, h, rd, "application/merge-patch+json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Record](resp)
}

func (g recordsRemote) Delete(ctx context.Context, collection string, id string, params *RecordsDeleteParams) error {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.IfMatch != nil {
			h.Set("If-Match", (*params.IfMatch))
		}
	}
	resp, err := g.t.do(ctx, "DELETE", "/records/"+url.PathEscape(collection)+"/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

type assetsRemote struct{ t *transport }

func (g assetsRemote) Upload(ctx context.Context, body io.Reader, contentType string, params *AssetsUploadParams) (*Asset, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		q.Add("kind", string(params.Kind))
		if params.Filename != nil {
			q.Add("filename", (*params.Filename))
		}
		if params.Pinned != nil {
			q.Add("pinned", strconv.FormatBool((*params.Pinned)))
		}
		if params.Width != nil {
			q.Add("width", strconv.FormatInt((*params.Width), 10))
		}
		if params.Height != nil {
			q.Add("height", strconv.FormatInt((*params.Height), 10))
		}
		if params.DurationS != nil {
			q.Add("duration_s", strconv.FormatFloat((*params.DurationS), 'g', -1, 64))
		}
		if params.FPS != nil {
			q.Add("fps", strconv.FormatFloat((*params.FPS), 'g', -1, 64))
		}
	}
	resp, err := g.t.do(ctx, "POST", "/assets", q, h, body, contentType)
	if err != nil {
		return nil, err
	}
	return decodeJSON[Asset](resp)
}

func (g assetsRemote) Adopt(ctx context.Context, body AdoptRequest) (*Asset, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/assets:adopt", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Asset](resp)
}

func (g assetsRemote) Read(ctx context.Context, id string, params *AssetsReadParams) (*RawResponse, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Range != nil {
			h.Set("Range", (*params.Range))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/assets/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return newRawResponse(resp), nil
}

func (g assetsRemote) Thumb(ctx context.Context, id string, params *AssetsThumbParams) (*RawResponse, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.W != nil {
			q.Add("w", strconv.FormatInt((*params.W), 10))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/assets/"+url.PathEscape(id)+"/thumb", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return newRawResponse(resp), nil
}

func (g assetsRemote) Lineage(ctx context.Context, id string, params *AssetsLineageParams) (*ItemPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/assets/"+url.PathEscape(id)+"/lineage", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[ItemPage](resp)
}

type galleryRemote struct{ t *transport }

func (g galleryRemote) Add(ctx context.Context, body ItemCreate) (*Item, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/gallery/items", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Item](resp)
}

func (g galleryRemote) Query(ctx context.Context, params *GalleryQueryParams) (*ItemPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Scope != nil {
			q.Add("scope", (*params.Scope))
		}
		if params.Studio != nil {
			q.Add("studio", (*params.Studio))
		}
		if params.Kind != nil {
			q.Add("kind", string((*params.Kind)))
		}
		for _, v := range params.Tag {
			q.Add("tag", v)
		}
		if params.SessionID != nil {
			q.Add("session_id", (*params.SessionID))
		}
		if params.Starred != nil {
			q.Add("starred", strconv.FormatBool((*params.Starred)))
		}
		if params.AssetID != nil {
			q.Add("asset_id", (*params.AssetID))
		}
		if params.Since != nil {
			q.Add("since", (*params.Since).Format(time.RFC3339Nano))
		}
		if params.Until != nil {
			q.Add("until", (*params.Until).Format(time.RFC3339Nano))
		}
		if params.Q != nil {
			q.Add("q", (*params.Q))
		}
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/gallery/items", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[ItemPage](resp)
}

func (g galleryRemote) Get(ctx context.Context, id string) (*Item, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/gallery/items/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Item](resp)
}

func (g galleryRemote) Update(ctx context.Context, id string, body map[string]any) (*Item, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PATCH", "/gallery/items/"+url.PathEscape(id), q, h, rd, "application/merge-patch+json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Item](resp)
}

func (g galleryRemote) Delete(ctx context.Context, id string) error {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "DELETE", "/gallery/items/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

func (g galleryRemote) Lineage(ctx context.Context, id string, params *GalleryLineageParams) (*ItemPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/gallery/items/"+url.PathEscape(id)+"/lineage", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[ItemPage](resp)
}

type handoffRemote struct{ t *transport }

func (g handoffRemote) Send(ctx context.Context, body HandoffRequest) (*Handoff, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/handoff", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Handoff](resp)
}

type inboxRemote struct{ t *transport }

func (g inboxRemote) List(ctx context.Context, params *InboxListParams) (*InboxPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/inbox", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[InboxPage](resp)
}

func (g inboxRemote) Consume(ctx context.Context, id string) error {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "POST", "/inbox/"+url.PathEscape(id)+":consume", q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

type jobsRemote struct{ t *transport }

func (g jobsRemote) List(ctx context.Context, params *JobsListParams) (*JobPage, error) {
	q := url.Values{}
	h := http.Header{}
	if params != nil {
		if params.Limit != nil {
			q.Add("limit", strconv.FormatInt((*params.Limit), 10))
		}
		if params.Cursor != nil {
			q.Add("cursor", (*params.Cursor))
		}
	}
	resp, err := g.t.do(ctx, "GET", "/jobs", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[JobPage](resp)
}

func (g jobsRemote) Create(ctx context.Context, body TaskCreate) (*Job, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "POST", "/jobs", q, h, rd, "application/json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Job](resp)
}

func (g jobsRemote) Get(ctx context.Context, id string) (*Job, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/jobs/"+url.PathEscape(id), q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Job](resp)
}

func (g jobsRemote) Update(ctx context.Context, id string, body map[string]any) (*Job, error) {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return nil, err
	}
	resp, err := g.t.do(ctx, "PATCH", "/jobs/"+url.PathEscape(id), q, h, rd, "application/merge-patch+json")
	if err != nil {
		return nil, err
	}
	return decodeJSON[Job](resp)
}

func (g jobsRemote) Cancel(ctx context.Context, id string) error {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "POST", "/jobs/"+url.PathEscape(id)+":cancel", q, h, nil, "")
	if err != nil {
		return err
	}
	return drain(resp)
}

func (g jobsRemote) Logs(ctx context.Context, id string) (*EventStream, error) {
	q := url.Values{}
	h := http.Header{}
	resp, err := g.t.do(ctx, "GET", "/jobs/"+url.PathEscape(id)+"/logs", q, h, nil, "")
	if err != nil {
		return nil, err
	}
	return newEventStream(resp), nil
}

func (g jobsRemote) AppendLog(ctx context.Context, id string, body LogAppend) error {
	q := url.Values{}
	h := http.Header{}
	rd, err := encodeJSON(body)
	if err != nil {
		return err
	}
	resp, err := g.t.do(ctx, "POST", "/jobs/"+url.PathEscape(id)+"/logs", q, h, rd, "application/json")
	if err != nil {
		return err
	}
	return drain(resp)
}
