// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.

package helm

import "time"

var _ = time.Time{}

// APIVersion is info.version of the contract these types were generated from.
const APIVersion = "1.0.0"

// Page is components.schemas.Page in api/openapi.yaml.
type Page struct {
	// Null on the last page.
	NextCursor *string `json:"next_cursor"`
}

// Me is components.schemas.Me in api/openapi.yaml.
type Me struct {
	StudioID     string       `json:"studio_id"`
	Capabilities []Capability `json:"capabilities"`
	Quota        MeQuota      `json:"quota"`
	Paths        MePaths      `json:"paths"`
	Provider     string       `json:"provider"`
	// This document's info.version.
	APIVersion string `json:"api_version"`
	// The daemon's or helm dev's build version.
	DaemonVersion string `json:"daemon_version"`
}

// QuotaUse is components.schemas.QuotaUse in api/openapi.yaml.
type QuotaUse struct {
	Limit int64 `json:"limit"`
	Used  int64 `json:"used"`
}

// Capability is components.schemas.Capability in api/openapi.yaml.
type Capability string

const (
	CapabilityKV             Capability = "kv"
	CapabilityRecords        Capability = "records"
	CapabilityAssets         Capability = "assets"
	CapabilityGallery        Capability = "gallery"
	CapabilityTimeline       Capability = "timeline"
	CapabilityJobs           Capability = "jobs"
	CapabilityGalleryReadAll Capability = "gallery.read_all"
	CapabilityKVShared       Capability = "kv.shared"
	CapabilityHandoffSend    Capability = "handoff.send"
)

// ThemeEvent is components.schemas.ThemeEvent in api/openapi.yaml.
type ThemeEvent struct {
	Theme string `json:"theme"`
}

// InboxEvent is components.schemas.InboxEvent in api/openapi.yaml.
type InboxEvent struct {
	InboxID    string  `json:"inbox_id"`
	ItemID     string  `json:"item_id"`
	FromStudio string  `json:"from_studio"`
	Role       *string `json:"role,omitempty"`
}

// ItemEvent is components.schemas.ItemEvent in api/openapi.yaml.
type ItemEvent struct {
	Change string `json:"change"`
	Item   Item   `json:"item"`
}

// JobEvent is components.schemas.JobEvent in api/openapi.yaml.
type JobEvent struct {
	Job Job `json:"job"`
}

// ShutdownEvent is components.schemas.ShutdownEvent in api/openapi.yaml.
type ShutdownEvent struct {
	Reason string `json:"reason"`
}

// GapEvent is components.schemas.GapEvent in api/openapi.yaml.
type GapEvent struct {
	// Events were lost; re-read state rather than trusting the stream.
	Reason string `json:"reason"`
}

// KVDoc is components.schemas.KVDoc in api/openapi.yaml.
type KVDoc struct {
	NS        string         `json:"ns"`
	Key       string         `json:"key"`
	Doc       map[string]any `json:"doc"`
	ETag      string         `json:"etag"`
	UpdatedAt time.Time      `json:"updated_at"`
}

// KVKey is components.schemas.KVKey in api/openapi.yaml.
type KVKey struct {
	Key       string    `json:"key"`
	Bytes     int64     `json:"bytes"`
	UpdatedAt time.Time `json:"updated_at"`
}

// KVKeyPage is components.schemas.KVKeyPage in api/openapi.yaml.
type KVKeyPage struct {
	// Null on the last page.
	NextCursor *string `json:"next_cursor"`
	Items      []KVKey `json:"items"`
}

// Session is components.schemas.Session in api/openapi.yaml.
type Session struct {
	ID        string         `json:"id"`
	StudioID  string         `json:"studio_id"`
	Name      string         `json:"name"`
	State     map[string]any `json:"state"`
	ETag      string         `json:"etag"`
	CreatedAt time.Time      `json:"created_at"`
	OpenedAt  *time.Time     `json:"opened_at"`
}

// SessionCreate is components.schemas.SessionCreate in api/openapi.yaml.
type SessionCreate struct {
	Name  string         `json:"name"`
	State map[string]any `json:"state,omitempty"`
}

// SessionUpdate: A JSON merge patch over the session's writable fields. `state` members
// merge; a null member removes that key.
type SessionUpdate struct {
	Name  *string        `json:"name,omitempty"`
	State map[string]any `json:"state,omitempty"`
}

// SessionDuplicate is components.schemas.SessionDuplicate in api/openapi.yaml.
type SessionDuplicate struct {
	Name string `json:"name"`
}

// SessionPage is components.schemas.SessionPage in api/openapi.yaml.
type SessionPage struct {
	// Null on the last page.
	NextCursor *string   `json:"next_cursor"`
	Items      []Session `json:"items"`
}

// Record is components.schemas.Record in api/openapi.yaml.
type Record struct {
	ID         string         `json:"id"`
	Collection string         `json:"collection"`
	Doc        map[string]any `json:"doc"`
	ETag       string         `json:"etag"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

// RecordPage is components.schemas.RecordPage in api/openapi.yaml.
type RecordPage struct {
	// Null on the last page.
	NextCursor *string  `json:"next_cursor"`
	Items      []Record `json:"items"`
}

// AssetKind is components.schemas.AssetKind in api/openapi.yaml.
type AssetKind string

const (
	AssetKindImage AssetKind = "image"
	AssetKindVideo AssetKind = "video"
	AssetKindAudio AssetKind = "audio"
	AssetKindOther AssetKind = "other"
)

// Asset is components.schemas.Asset in api/openapi.yaml.
type Asset struct {
	ID        string    `json:"id"`
	SHA256    string    `json:"sha256"`
	Kind      AssetKind `json:"kind"`
	Mime      string    `json:"mime"`
	Bytes     int64     `json:"bytes"`
	Width     *int64    `json:"width"`
	Height    *int64    `json:"height"`
	DurationS *float64  `json:"duration_s"`
	FPS       *float64  `json:"fps"`
	State     string    `json:"state"`
	Pinned    bool      `json:"pinned"`
	// The studio that first stored these bytes. Null for any caller that is not that
	// studio, so a dedup hit or a shared read never reveals another studio (M4 first
	// review, #9).
	OriginStudio *string `json:"origin_studio"`
	// This API's path to the bytes, e.g. /api/v1/assets/{id}. Needs the Bearer header
	// until M6 decides browser access.
	URL string `json:"url"`
	// This API's path to the thumbnail, e.g. /api/v1/assets/{id}/thumb?w=320. Needs the
	// Bearer header until M6 decides browser access.
	Thumb string `json:"thumb"`
	// The readable hardlink, relative to the library root. Null when it could not be made
	// (Q11), and null for any caller that is not the origin studio, since it names that
	// studio, a month and a filename (M4 first review, #9).
	LibraryPath *string   `json:"library_path"`
	CreatedAt   time.Time `json:"created_at"`
	// Present on an adopt or upload response when something short of failure happened,
	// such as no library link.
	Warnings []string `json:"warnings,omitempty"`
}

// AdoptRequest is components.schemas.AdoptRequest in api/openapi.yaml.
type AdoptRequest struct {
	// Absolute, inside the caller's stage directory (unlinked after adopting) or its data
	// directory (left in place, read-only).
	Path      string    `json:"path"`
	Kind      AssetKind `json:"kind"`
	Pinned    *bool     `json:"pinned,omitempty"`
	Width     *int64    `json:"width,omitempty"`
	Height    *int64    `json:"height,omitempty"`
	DurationS *float64  `json:"duration_s,omitempty"`
	FPS       *float64  `json:"fps,omitempty"`
}

// ItemInput is components.schemas.ItemInput in api/openapi.yaml.
type ItemInput struct {
	AssetID string `json:"asset_id"`
	// e.g. first_frame, last_frame, reference, audio_bed, clip
	Role string `json:"role"`
}

// ItemCreate is components.schemas.ItemCreate in api/openapi.yaml.
type ItemCreate struct {
	Kind      AssetKind      `json:"kind"`
	AssetID   string         `json:"asset_id"`
	Title     *string        `json:"title,omitempty"`
	SessionID *string        `json:"session_id,omitempty"`
	Params    map[string]any `json:"params"`
	Inputs    []ItemInput    `json:"inputs,omitempty"`
	Tags      []string       `json:"tags,omitempty"`
}

// ItemUpdate is components.schemas.ItemUpdate in api/openapi.yaml.
type ItemUpdate struct {
	Title   *string  `json:"title,omitempty"`
	Starred *bool    `json:"starred,omitempty"`
	Tags    []string `json:"tags,omitempty"`
}

// Item is components.schemas.Item in api/openapi.yaml.
type Item struct {
	ID        string         `json:"id"`
	StudioID  string         `json:"studio_id"`
	Kind      AssetKind      `json:"kind"`
	AssetID   string         `json:"asset_id"`
	Asset     Asset          `json:"asset"`
	SessionID *string        `json:"session_id"`
	Title     *string        `json:"title"`
	Params    map[string]any `json:"params"`
	Starred   bool           `json:"starred"`
	Tags      []string       `json:"tags"`
	Inputs    []ItemInput    `json:"inputs"`
	CreatedAt time.Time      `json:"created_at"`
}

// ItemPage is components.schemas.ItemPage in api/openapi.yaml.
type ItemPage struct {
	// Null on the last page.
	NextCursor *string `json:"next_cursor"`
	Items      []Item  `json:"items"`
}

// HandoffRequest is components.schemas.HandoffRequest in api/openapi.yaml.
type HandoffRequest struct {
	ItemID   string  `json:"item_id"`
	ToStudio string  `json:"to_studio"`
	Role     *string `json:"role,omitempty"`
}

// Handoff is components.schemas.Handoff in api/openapi.yaml.
type Handoff struct {
	ID        string    `json:"id"`
	ToStudio  string    `json:"to_studio"`
	ItemID    string    `json:"item_id"`
	Role      *string   `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// InboxEntry is components.schemas.InboxEntry in api/openapi.yaml.
type InboxEntry struct {
	ID         string `json:"id"`
	FromStudio string `json:"from_studio"`
	ItemID     string `json:"item_id"`
	// Null when the sender has since deleted the item.
	Item      *Item     `json:"item"`
	Role      *string   `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// InboxPage is components.schemas.InboxPage in api/openapi.yaml.
type InboxPage struct {
	// Null on the last page.
	NextCursor *string      `json:"next_cursor"`
	Items      []InboxEntry `json:"items"`
}

// JobKind is components.schemas.JobKind in api/openapi.yaml.
type JobKind string

const (
	JobKindInstall   JobKind = "install"
	JobKindBuild     JobKind = "build"
	JobKindDownload  JobKind = "download"
	JobKindUpdate    JobKind = "update"
	JobKindExport    JobKind = "export"
	JobKindUninstall JobKind = "uninstall"
	JobKindTask      JobKind = "task"
)

// JobState is components.schemas.JobState in api/openapi.yaml.
type JobState string

const (
	JobStateQueued      JobState = "queued"
	JobStateRunning     JobState = "running"
	JobStateSucceeded   JobState = "succeeded"
	JobStateFailed      JobState = "failed"
	JobStateCancelled   JobState = "cancelled"
	JobStateInterrupted JobState = "interrupted"
)

// JobError: installations.last_failure and jobs.last_error (02 §4). Install codes:
// clone_failed, tool_missing, env_failed, step_failed, step_timeout, cancelled,
// interrupted, auth_required, disk_space, weights_failed, linked_missing,
// uninstall_failed. env_failed (creating a Python environment, docs/decisions.md M5 Q7)
// has no step_index. A task job's code is the studio's own.
type JobError struct {
	Code      string  `json:"code"`
	Message   string  `json:"message"`
	Phase     *string `json:"phase,omitempty"`
	StepIndex *int64  `json:"step_index,omitempty"`
	ExitCode  *int64  `json:"exit_code,omitempty"`
	LogFileID *string `json:"log_file_id,omitempty"`
}

// StepRun is components.schemas.StepRun in api/openapi.yaml.
type StepRun struct {
	StepIndex  int64      `json:"step_index"`
	StepName   string     `json:"step_name"`
	Command    string     `json:"command"`
	State      string     `json:"state"`
	ExitCode   *int64     `json:"exit_code,omitempty"`
	LogFileID  *string    `json:"log_file_id,omitempty"`
	StartedAt  *time.Time `json:"started_at,omitempty"`
	FinishedAt *time.Time `json:"finished_at,omitempty"`
}

// Job is components.schemas.Job in api/openapi.yaml.
type Job struct {
	ID                string     `json:"id"`
	Kind              JobKind    `json:"kind"`
	StudioID          *string    `json:"studio_id,omitempty"`
	State             JobState   `json:"state"`
	SubjectKind       *string    `json:"subject_kind,omitempty"`
	SubjectID         *string    `json:"subject_id,omitempty"`
	ProgressNum       int64      `json:"progress_num"`
	ProgressDen       int64      `json:"progress_den"`
	LastError         *JobError  `json:"last_error,omitempty"`
	CreatedAt         time.Time  `json:"created_at"`
	StartedAt         *time.Time `json:"started_at,omitempty"`
	FinishedAt        *time.Time `json:"finished_at,omitempty"`
	CancelRequestedAt *time.Time `json:"cancel_requested_at,omitempty"`
	Steps             []StepRun  `json:"steps,omitempty"`
	Warnings          []string   `json:"warnings,omitempty"`
}

// JobPage is components.schemas.JobPage in api/openapi.yaml.
type JobPage struct {
	// Null on the last page.
	NextCursor *string `json:"next_cursor"`
	Items      []Job   `json:"items"`
}

// TaskCreate is components.schemas.TaskCreate in api/openapi.yaml.
type TaskCreate struct {
	State       *string `json:"state,omitempty"`
	SubjectKind *string `json:"subject_kind,omitempty"`
	SubjectID   *string `json:"subject_id,omitempty"`
	ProgressNum *int64  `json:"progress_num,omitempty"`
	ProgressDen *int64  `json:"progress_den,omitempty"`
}

// TaskUpdate is components.schemas.TaskUpdate in api/openapi.yaml.
type TaskUpdate struct {
	State       *string              `json:"state,omitempty"`
	ProgressNum *int64               `json:"progress_num,omitempty"`
	ProgressDen *int64               `json:"progress_den,omitempty"`
	LastError   *TaskUpdateLastError `json:"last_error,omitempty"`
}

// LogAppend is components.schemas.LogAppend in api/openapi.yaml.
type LogAppend struct {
	Lines []string `json:"lines"`
}

// JobLogStep is components.schemas.JobLogStep in api/openapi.yaml.
type JobLogStep struct {
	StepIndex int64  `json:"step_index"`
	StepName  string `json:"step_name"`
	Command   string `json:"command"`
}

// JobLogLine is components.schemas.JobLogLine in api/openapi.yaml.
type JobLogLine struct {
	// Absent for a task job.
	StepIndex *int64 `json:"step_index,omitempty"`
	Text      string `json:"text"`
}

// JobLogEnd is components.schemas.JobLogEnd in api/openapi.yaml.
type JobLogEnd struct {
	State     JobState  `json:"state"`
	LastError *JobError `json:"last_error,omitempty"`
}

// EventsSubscribeParams holds the query and header parameters of GET /events.
type EventsSubscribeParams struct {
	LastEventID *string
}

// KVListParams holds the query and header parameters of GET /kv/{ns}.
type KVListParams struct {
	Prefix *string
	Limit  *int64
	Cursor *string
}

// KVPutParams holds the query and header parameters of PUT /kv/{ns}/{key}.
type KVPutParams struct {
	IfMatch *string
}

// KVPatchParams holds the query and header parameters of PATCH /kv/{ns}/{key}.
type KVPatchParams struct {
	IfMatch *string
}

// KVDeleteParams holds the query and header parameters of DELETE /kv/{ns}/{key}.
type KVDeleteParams struct {
	IfMatch *string
}

// SessionsListParams holds the query and header parameters of GET /sessions.
type SessionsListParams struct {
	Limit  *int64
	Cursor *string
}

// SessionsUpdateParams holds the query and header parameters of PATCH /sessions/{id}.
type SessionsUpdateParams struct {
	IfMatch *string
}

// SessionsDeleteParams holds the query and header parameters of DELETE /sessions/{id}.
type SessionsDeleteParams struct {
	IfMatch *string
}

// RecordsQueryParams holds the query and header parameters of GET /records/{collection}.
type RecordsQueryParams struct {
	Where  []string
	Order  *string
	Limit  *int64
	Cursor *string
}

// RecordsReplaceParams holds the query and header parameters of PUT /records/{collection}/{id}.
type RecordsReplaceParams struct {
	IfMatch *string
}

// RecordsPatchParams holds the query and header parameters of PATCH /records/{collection}/{id}.
type RecordsPatchParams struct {
	IfMatch *string
}

// RecordsDeleteParams holds the query and header parameters of DELETE /records/{collection}/{id}.
type RecordsDeleteParams struct {
	IfMatch *string
}

// AssetsUploadParams holds the query and header parameters of POST /assets.
type AssetsUploadParams struct {
	Kind      AssetKind
	Filename  *string
	Pinned    *bool
	Width     *int64
	Height    *int64
	DurationS *float64
	FPS       *float64
}

// AssetsReadParams holds the query and header parameters of GET /assets/{id}.
type AssetsReadParams struct {
	Range *string
}

// AssetsThumbParams holds the query and header parameters of GET /assets/{id}/thumb.
type AssetsThumbParams struct {
	W *int64
}

// AssetsLineageParams holds the query and header parameters of GET /assets/{id}/lineage.
type AssetsLineageParams struct {
	Limit  *int64
	Cursor *string
}

// GalleryQueryParams holds the query and header parameters of GET /gallery/items.
type GalleryQueryParams struct {
	Scope     *string
	Studio    *string
	Kind      *AssetKind
	Tag       []string
	SessionID *string
	Starred   *bool
	AssetID   *string
	Since     *time.Time
	Until     *time.Time
	Q         *string
	Limit     *int64
	Cursor    *string
}

// GalleryLineageParams holds the query and header parameters of GET /gallery/items/{id}/lineage.
type GalleryLineageParams struct {
	Limit  *int64
	Cursor *string
}

// InboxListParams holds the query and header parameters of GET /inbox.
type InboxListParams struct {
	Limit  *int64
	Cursor *string
}

// JobsListParams holds the query and header parameters of GET /jobs.
type JobsListParams struct {
	Limit  *int64
	Cursor *string
}

// MeQuota is components.schemas.MeQuota in api/openapi.yaml.
type MeQuota struct {
	Records QuotaUse `json:"records"`
	KVBytes QuotaUse `json:"kv_bytes"`
}

// MePaths is components.schemas.MePaths in api/openapi.yaml.
type MePaths struct {
	// Absolute. The directory :adopt takes files from.
	Stage string `json:"stage"`
	// Absolute. The studio's persistent data directory, {data}.
	Data string `json:"data"`
}

// TaskUpdateLastError is components.schemas.TaskUpdateLastError in api/openapi.yaml.
type TaskUpdateLastError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
