// Package studioapi is the studio-facing half of api/openapi.yaml: every
// operation tagged studio-api, enforced once and served by both providers
// (docs/decisions.md, M4 Q25 and the store-home answer).
//
// zz_server.go is generated by api/gen: the Server interface, one route per
// operation, parameter and body decoding, and the checks the contract's
// schemas state. Service implements Server. Handler is the router: it
// authenticates, applies the operation's x-helm-capability, and calls Service.
// The daemon mounts Handler with token authentication; the embedded provider
// mounts the same Handler with a principal read from the studio's manifest.
package studioapi

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"regexp"
	"sort"
	"strings"

	helm "github.com/janishar/helmstudio/packages/helm-runtime-sdk/go"
)

// Base is the API prefix every route sits under.
const Base = "/api/v1"

// MaxJSONBody caps every JSON request body (api/openapi.yaml conventions).
const MaxJSONBody = 1 << 20

type route struct {
	method     string
	path       string
	operation  string
	capability string
	serve      func(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string)
	segs       []segment
}

// segment is one path segment: a literal, or {param} with an optional
// ":action" suffix.
type segment struct {
	literal string
	param   bool
	suffix  string
}

func parsePath(p string) []segment {
	var out []segment
	for _, s := range strings.Split(strings.TrimPrefix(p, "/"), "/") {
		if i := strings.Index(s, "{"); i == 0 {
			j := strings.Index(s, "}")
			out = append(out, segment{param: true, suffix: s[j+1:]})
		} else {
			out = append(out, segment{literal: s})
		}
	}
	return out
}

func init() {
	for i := range routes {
		routes[i].segs = parsePath(routes[i].path)
	}
	// A route whose parameter carries an action — /timeline/{id}:plan — is more
	// specific than the bare /timeline/{id}, and both match the same path. Try
	// the specific one first, or a GET action would be read as an id ending in
	// ":plan" and refused for not looking like one.
	sort.SliceStable(routes, func(i, j int) bool { return specificity(routes[i]) > specificity(routes[j]) })
}

// specificity counts the parameters that carry an action.
func specificity(rt route) int {
	n := 0
	for _, s := range rt.segs {
		if s.param && s.suffix != "" {
			n++
		}
	}
	return n
}

// match returns the path values when path fits r.
func (rt *route) match(parts []string) ([]string, bool) {
	if len(parts) != len(rt.segs) {
		return nil, false
	}
	var pv []string
	for i, s := range rt.segs {
		if !s.param {
			if parts[i] != s.literal {
				return nil, false
			}
			continue
		}
		raw := parts[i]
		if s.suffix != "" {
			if !strings.HasSuffix(raw, s.suffix) || len(raw) == len(s.suffix) {
				return nil, false
			}
			raw = strings.TrimSuffix(raw, s.suffix)
		}
		v, err := url.PathUnescape(raw)
		if err != nil || v == "" {
			return nil, false
		}
		pv = append(pv, v)
	}
	return pv, true
}

// Authenticator turns a request into a context carrying its Principal.
type Authenticator func(r *http.Request) (context.Context, error)

// Handler routes studio-api requests to a Server.
type Handler struct {
	srv  Server
	auth Authenticator
	logf func(string, ...any)
}

// NewHandler returns the router for srv.
func NewHandler(srv Server, auth Authenticator, logf func(string, ...any)) *Handler {
	if logf == nil {
		logf = func(string, ...any) {}
	}
	return &Handler{srv: srv, auth: auth, logf: logf}
}

// Serve answers r when its path is a studio-api route and reports whether it
// did. A path no route has is left to the caller.
func (h *Handler) Serve(w http.ResponseWriter, r *http.Request) bool {
	path := r.URL.EscapedPath()
	if !strings.HasPrefix(path, Base+"/") {
		return false
	}
	parts := strings.Split(strings.TrimPrefix(path, Base+"/"), "/")
	var allowed []string
	for i := range routes {
		rt := &routes[i]
		pv, ok := rt.match(parts)
		if !ok {
			continue
		}
		if rt.method != r.Method {
			allowed = append(allowed, rt.method)
			continue
		}
		ctx, err := h.auth(r)
		if err != nil {
			h.fail(w, r, err)
			return true
		}
		if err := allow(ctx, rt.capability); err != nil {
			h.fail(w, r, err)
			return true
		}
		rt.serve(ctx, h, w, r, pv)
		return true
	}
	if len(allowed) > 0 {
		w.Header().Set("Allow", strings.Join(allowed, ", "))
		writeError(w, &helm.Error{Status: http.StatusMethodNotAllowed, Code: "method_not_allowed",
			Message: fmt.Sprintf("%s is not allowed on %s; use %s", r.Method, path, strings.Join(allowed, " or "))})
		return true
	}
	return false
}

// ServeHTTP answers every request, with 404 for a path no route has.
func (h *Handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if !h.Serve(w, r) {
		writeError(w, notFound("no operation at %s", r.URL.Path))
	}
}

// Operation is one studio-api route.
type Operation struct {
	Method, Path, ID, Capability string
}

// Operations lists every studio-api route, generated from api/openapi.yaml, so
// a test can try each one without keeping its own list (second review #4).
func Operations() []Operation {
	out := make([]Operation, len(routes))
	for i, rt := range routes {
		out[i] = Operation{Method: rt.method, Path: rt.path, ID: rt.operation, Capability: rt.capability}
	}
	return out
}

func (h *Handler) fail(w http.ResponseWriter, r *http.Request, err error) {
	var e *helm.Error
	if !errors.As(err, &e) {
		h.logf("studioapi: %s %s: %v", r.Method, r.URL.Path, err)
		e = &helm.Error{Status: http.StatusInternalServerError, Code: "internal", Message: err.Error()}
	}
	writeError(w, e)
}

func writeError(w http.ResponseWriter, e *helm.Error) {
	writeJSON(w, e.Status, e)
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// setETag sends an etag quoted, as HTTP spells it.
func setETag(w http.ResponseWriter, etag string) {
	w.Header().Set("ETag", `"`+etag+`"`)
}

// unquoteETag accepts If-Match with or without quotes, and a weak prefix.
func unquoteETag(v string) string {
	v = strings.TrimPrefix(strings.TrimSpace(v), "W/")
	return strings.Trim(v, `"`)
}

func readRaw(w http.ResponseWriter, r *http.Request) ([]byte, error) {
	raw, err := io.ReadAll(http.MaxBytesReader(w, r.Body, MaxJSONBody))
	if err != nil {
		var mbe *http.MaxBytesError
		if errors.As(err, &mbe) {
			return nil, &helm.Error{Status: http.StatusRequestEntityTooLarge, Code: "too_large",
				Message: fmt.Sprintf("the request body is over %d bytes", MaxJSONBody), Details: map[string]any{"limit": MaxJSONBody}}
		}
		return nil, badRequest("reading the request body: %v", err)
	}
	return raw, nil
}

// readBody decodes a JSON object into dst, refusing unknown members (every
// request schema is additionalProperties: false) and missing required ones.
func readBody(w http.ResponseWriter, r *http.Request, dst any, required []string) error {
	raw, err := readRaw(w, r)
	if err != nil {
		return err
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(raw, &members); err != nil || members == nil {
		return badRequest("the body must be a JSON object")
	}
	for _, k := range required {
		if v, ok := members[k]; !ok || string(v) == "null" {
			return badRequest("%s is required", k)
		}
	}
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.UseNumber() // params and documents keep integers exact
	dec.DisallowUnknownFields()
	if err := dec.Decode(dst); err != nil {
		return badRequest("the body does not match its schema: %v", err)
	}
	return nil
}

// readObject decodes a JSON object as a map: a merge patch, or a document.
// allowed, when not nil, is the set of members the schema permits.
func readObject(w http.ResponseWriter, r *http.Request, dst *map[string]any, allowed []string, minProps int) error {
	raw, err := readRaw(w, r)
	if err != nil {
		return err
	}
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.UseNumber()
	var v map[string]any
	if err := dec.Decode(&v); err != nil || v == nil {
		return badRequest("the body must be a JSON object")
	}
	if allowed != nil {
		for k := range v {
			ok := false
			for _, a := range allowed {
				ok = ok || a == k
			}
			if !ok {
				return badRequest("%s is not a field this operation accepts", k)
			}
		}
	}
	if len(v) < minProps {
		return badRequest("the body must set at least %d field(s)", minProps)
	}
	*dst = normalizeNumbers(v).(map[string]any)
	return nil
}

// normalizeNumbers turns json.Number into int64 when integral, else float64,
// so documents round-trip without losing integer precision.
func normalizeNumbers(v any) any {
	switch t := v.(type) {
	case json.Number:
		if i, err := t.Int64(); err == nil {
			return i
		}
		f, _ := t.Float64()
		return f
	case map[string]any:
		for k, x := range t {
			t[k] = normalizeNumbers(x)
		}
		return t
	case []any:
		for i, x := range t {
			t[i] = normalizeNumbers(x)
		}
		return t
	}
	return v
}

func badParam(name, reason string) error { return badRequest("%s %s", name, reason) }

func checkPattern(field, v string, re *regexp.Regexp) error {
	if !re.MatchString(v) {
		return badRequest("%s %q does not match %s", field, v, re.String())
	}
	return nil
}

func checkLength(field, v string, min, max int64) error {
	n := int64(len([]rune(v)))
	if (min >= 0 && n < min) || (max >= 0 && n > max) {
		return badRequest("%s must be between %d and %d characters", field, max0(min), max)
	}
	return nil
}

func max0(v int64) int64 { return max(v, 0) }

func checkEnum(field, v string, allowed []string) error {
	for _, a := range allowed {
		if a == v {
			return nil
		}
	}
	return badRequest("%s must be one of %s", field, strings.Join(allowed, ", "))
}

func checkRange(field string, v float64, min, max, exclMin *float64) error {
	if (min != nil && v < *min) || (max != nil && v > *max) || (exclMin != nil && v <= *exclMin) {
		return badRequest("%s %v is out of range", field, v)
	}
	return nil
}

func checkItems(field string, n int, min, max int64) error {
	if (min >= 0 && int64(n) < min) || (max >= 0 && int64(n) > max) {
		return badRequest("%s must have between %d and %d items", field, max0(min), max)
	}
	return nil
}

func ptrFloat(v float64) *float64 { return &v }

func firstError(errs ...error) error {
	for _, e := range errs {
		if e != nil {
			return e
		}
	}
	return nil
}
