// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.

package studioapi

import (
	"context"
	"io"
	"net/http"
	"regexp"
	"strconv"
	"time"

	helm "github.com/janishar/helmstudio/packages/helm-runtime-sdk/go"
)

var (
	_ = io.EOF
	_ = strconv.Itoa
	_ = time.RFC3339
	_ = regexp.MustCompile
)

// Server is every studio-api operation. It is implemented once, by Service,
// and the same router serves it to the daemon and to the embedded provider.
type Server interface {
	MeGet(ctx context.Context) (*helm.Me, error)
	EventsSubscribe(ctx context.Context, w http.ResponseWriter, r *http.Request, params helm.EventsSubscribeParams) error
	KVList(ctx context.Context, ns string, params helm.KVListParams) (*helm.KVKeyPage, error)
	KVGet(ctx context.Context, ns string, key string) (*helm.KVDoc, error)
	KVPut(ctx context.Context, ns string, key string, body map[string]any, params helm.KVPutParams) (*helm.KVDoc, error)
	KVPatch(ctx context.Context, ns string, key string, body map[string]any, params helm.KVPatchParams) (*helm.KVDoc, error)
	KVDelete(ctx context.Context, ns string, key string, params helm.KVDeleteParams) error
	SessionsList(ctx context.Context, params helm.SessionsListParams) (*helm.SessionPage, error)
	SessionsCreate(ctx context.Context, body *helm.SessionCreate) (*helm.Session, error)
	SessionsGet(ctx context.Context, id string) (*helm.Session, error)
	SessionsUpdate(ctx context.Context, id string, body map[string]any, params helm.SessionsUpdateParams) (*helm.Session, error)
	SessionsDelete(ctx context.Context, id string, params helm.SessionsDeleteParams) error
	SessionsDuplicate(ctx context.Context, id string, body *helm.SessionDuplicate) (*helm.Session, error)
	SessionsActivate(ctx context.Context, id string) error
	RecordsQuery(ctx context.Context, collection string, params helm.RecordsQueryParams) (*helm.RecordPage, error)
	RecordsInsert(ctx context.Context, collection string, body map[string]any) (*helm.Record, error)
	RecordsGet(ctx context.Context, collection string, id string) (*helm.Record, error)
	RecordsReplace(ctx context.Context, collection string, id string, body map[string]any, params helm.RecordsReplaceParams) (*helm.Record, error)
	RecordsPatch(ctx context.Context, collection string, id string, body map[string]any, params helm.RecordsPatchParams) (*helm.Record, error)
	RecordsDelete(ctx context.Context, collection string, id string, params helm.RecordsDeleteParams) error
	AssetsUpload(ctx context.Context, body io.Reader, contentType string, contentLength int64, params helm.AssetsUploadParams) (*helm.Asset, bool, error)
	AssetsAdopt(ctx context.Context, body *helm.AdoptRequest) (*helm.Asset, bool, error)
	AssetsRead(ctx context.Context, w http.ResponseWriter, r *http.Request, id string, params helm.AssetsReadParams) error
	AssetsThumb(ctx context.Context, w http.ResponseWriter, r *http.Request, id string, params helm.AssetsThumbParams) error
	AssetsLineage(ctx context.Context, id string, params helm.AssetsLineageParams) (*helm.ItemPage, error)
	GalleryAdd(ctx context.Context, body *helm.ItemCreate) (*helm.Item, error)
	GalleryQuery(ctx context.Context, params helm.GalleryQueryParams) (*helm.ItemPage, error)
	GalleryGet(ctx context.Context, id string) (*helm.Item, error)
	GalleryUpdate(ctx context.Context, id string, body map[string]any) (*helm.Item, error)
	GalleryDelete(ctx context.Context, id string) error
	GalleryLineage(ctx context.Context, id string, params helm.GalleryLineageParams) (*helm.ItemPage, error)
	HandoffSend(ctx context.Context, body *helm.HandoffRequest) (*helm.Handoff, error)
	InboxList(ctx context.Context, params helm.InboxListParams) (*helm.InboxPage, error)
	InboxConsume(ctx context.Context, id string) error
	JobsList(ctx context.Context, params helm.JobsListParams) (*helm.JobPage, error)
	JobsCreate(ctx context.Context, body *helm.TaskCreate) (*helm.Job, error)
	JobsGet(ctx context.Context, id string) (*helm.Job, error)
	JobsUpdate(ctx context.Context, id string, body map[string]any) (*helm.Job, error)
	JobsCancel(ctx context.Context, id string) error
	JobsLogs(ctx context.Context, w http.ResponseWriter, r *http.Request, id string) error
	JobsAppendLog(ctx context.Context, id string, body *helm.LogAppend) error
}

var routes = []route{
	{method: "GET", path: "/me", operation: "meGet", capability: "token", serve: serveMeGet},
	{method: "GET", path: "/events", operation: "eventsSubscribe", capability: "token", serve: serveEventsSubscribe},
	{method: "GET", path: "/kv/{ns}", operation: "kvList", capability: "kv", serve: serveKVList},
	{method: "GET", path: "/kv/{ns}/{key}", operation: "kvGet", capability: "kv", serve: serveKVGet},
	{method: "PUT", path: "/kv/{ns}/{key}", operation: "kvPut", capability: "kv", serve: serveKVPut},
	{method: "PATCH", path: "/kv/{ns}/{key}", operation: "kvPatch", capability: "kv", serve: serveKVPatch},
	{method: "DELETE", path: "/kv/{ns}/{key}", operation: "kvDelete", capability: "kv", serve: serveKVDelete},
	{method: "GET", path: "/sessions", operation: "sessionsList", capability: "kv", serve: serveSessionsList},
	{method: "POST", path: "/sessions", operation: "sessionsCreate", capability: "kv", serve: serveSessionsCreate},
	{method: "GET", path: "/sessions/{id}", operation: "sessionsGet", capability: "kv", serve: serveSessionsGet},
	{method: "PATCH", path: "/sessions/{id}", operation: "sessionsUpdate", capability: "kv", serve: serveSessionsUpdate},
	{method: "DELETE", path: "/sessions/{id}", operation: "sessionsDelete", capability: "kv", serve: serveSessionsDelete},
	{method: "POST", path: "/sessions/{id}:duplicate", operation: "sessionsDuplicate", capability: "kv", serve: serveSessionsDuplicate},
	{method: "POST", path: "/sessions/{id}:activate", operation: "sessionsActivate", capability: "kv", serve: serveSessionsActivate},
	{method: "GET", path: "/records/{collection}", operation: "recordsQuery", capability: "records", serve: serveRecordsQuery},
	{method: "POST", path: "/records/{collection}", operation: "recordsInsert", capability: "records", serve: serveRecordsInsert},
	{method: "GET", path: "/records/{collection}/{id}", operation: "recordsGet", capability: "records", serve: serveRecordsGet},
	{method: "PUT", path: "/records/{collection}/{id}", operation: "recordsReplace", capability: "records", serve: serveRecordsReplace},
	{method: "PATCH", path: "/records/{collection}/{id}", operation: "recordsPatch", capability: "records", serve: serveRecordsPatch},
	{method: "DELETE", path: "/records/{collection}/{id}", operation: "recordsDelete", capability: "records", serve: serveRecordsDelete},
	{method: "POST", path: "/assets", operation: "assetsUpload", capability: "assets", serve: serveAssetsUpload},
	{method: "POST", path: "/assets:adopt", operation: "assetsAdopt", capability: "assets", serve: serveAssetsAdopt},
	{method: "GET", path: "/assets/{id}", operation: "assetsRead", capability: "assets", serve: serveAssetsRead},
	{method: "GET", path: "/assets/{id}/thumb", operation: "assetsThumb", capability: "assets", serve: serveAssetsThumb},
	{method: "GET", path: "/assets/{id}/lineage", operation: "assetsLineage", capability: "gallery", serve: serveAssetsLineage},
	{method: "POST", path: "/gallery/items", operation: "galleryAdd", capability: "gallery", serve: serveGalleryAdd},
	{method: "GET", path: "/gallery/items", operation: "galleryQuery", capability: "gallery", serve: serveGalleryQuery},
	{method: "GET", path: "/gallery/items/{id}", operation: "galleryGet", capability: "gallery", serve: serveGalleryGet},
	{method: "PATCH", path: "/gallery/items/{id}", operation: "galleryUpdate", capability: "gallery", serve: serveGalleryUpdate},
	{method: "DELETE", path: "/gallery/items/{id}", operation: "galleryDelete", capability: "gallery", serve: serveGalleryDelete},
	{method: "GET", path: "/gallery/items/{id}/lineage", operation: "galleryLineage", capability: "gallery", serve: serveGalleryLineage},
	{method: "POST", path: "/handoff", operation: "handoffSend", capability: "handoff.send", serve: serveHandoffSend},
	{method: "GET", path: "/inbox", operation: "inboxList", capability: "gallery", serve: serveInboxList},
	{method: "POST", path: "/inbox/{id}:consume", operation: "inboxConsume", capability: "gallery", serve: serveInboxConsume},
	{method: "GET", path: "/jobs", operation: "jobsList", capability: "jobs", serve: serveJobsList},
	{method: "POST", path: "/jobs", operation: "jobsCreate", capability: "jobs", serve: serveJobsCreate},
	{method: "GET", path: "/jobs/{id}", operation: "jobsGet", capability: "jobs", serve: serveJobsGet},
	{method: "PATCH", path: "/jobs/{id}", operation: "jobsUpdate", capability: "jobs", serve: serveJobsUpdate},
	{method: "POST", path: "/jobs/{id}:cancel", operation: "jobsCancel", capability: "jobs", serve: serveJobsCancel},
	{method: "GET", path: "/jobs/{id}/logs", operation: "jobsLogs", capability: "jobs", serve: serveJobsLogs},
	{method: "POST", path: "/jobs/{id}/logs", operation: "jobsAppendLog", capability: "jobs", serve: serveJobsAppendLog},
}

func serveMeGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	res, err := h.srv.MeGet(ctx)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveEventsSubscribe(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.EventsSubscribeParams
	if vs := r.Header.Values("Last-Event-ID"); len(vs) > 0 {
		v_last_event_id := vs[0]
		params.LastEventID = &v_last_event_id
	}
	if err := h.srv.EventsSubscribe(ctx, w, r, params); err != nil {
		h.fail(w, r, err)
	}
}

func serveKVList(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	ns := pv[0]
	if err := checkPattern("ns", ns, pattern0); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.KVListParams
	query := r.URL.Query()
	if vs := query["prefix"]; len(vs) > 0 {
		v_prefix := vs[0]
		if err := checkLength("prefix", v_prefix, -1, 200); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Prefix = &v_prefix
	}
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.KVList(ctx, ns, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveKVGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	ns := pv[0]
	if err := checkPattern("ns", ns, pattern1); err != nil {
		h.fail(w, r, err)
		return
	}
	key := pv[1]
	if err := checkPattern("key", key, pattern2); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.KVGet(ctx, ns, key)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveKVPut(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	ns := pv[0]
	if err := checkPattern("ns", ns, pattern3); err != nil {
		h.fail(w, r, err)
		return
	}
	key := pv[1]
	if err := checkPattern("key", key, pattern4); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, nil, 0); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.KVPutParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	res, err := h.srv.KVPut(ctx, ns, key, body, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveKVPatch(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	ns := pv[0]
	if err := checkPattern("ns", ns, pattern5); err != nil {
		h.fail(w, r, err)
		return
	}
	key := pv[1]
	if err := checkPattern("key", key, pattern6); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, nil, 0); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.KVPatchParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	res, err := h.srv.KVPatch(ctx, ns, key, body, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveKVDelete(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	ns := pv[0]
	if err := checkPattern("ns", ns, pattern7); err != nil {
		h.fail(w, r, err)
		return
	}
	key := pv[1]
	if err := checkPattern("key", key, pattern8); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.KVDeleteParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	if err := h.srv.KVDelete(ctx, ns, key, params); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveSessionsList(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.SessionsListParams
	query := r.URL.Query()
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.SessionsList(ctx, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveSessionsCreate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var body helm.SessionCreate
	if err := readBody(w, r, &body, []string{"name"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateSessionCreate(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.SessionsCreate(ctx, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 201, res)
}

func serveSessionsGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern9); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.SessionsGet(ctx, id)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveSessionsUpdate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern10); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, []string{"name", "state"}, 1); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.SessionsUpdateParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	res, err := h.srv.SessionsUpdate(ctx, id, body, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveSessionsDelete(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern11); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.SessionsDeleteParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	if err := h.srv.SessionsDelete(ctx, id, params); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveSessionsDuplicate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern12); err != nil {
		h.fail(w, r, err)
		return
	}
	var body helm.SessionDuplicate
	if err := readBody(w, r, &body, []string{"name"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateSessionDuplicate(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.SessionsDuplicate(ctx, id, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 201, res)
}

func serveSessionsActivate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern13); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.SessionsActivate(ctx, id); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveRecordsQuery(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern14), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.RecordsQueryParams
	query := r.URL.Query()
	params.Where = query["where"]
	if len(params.Where) > 8 {
		h.fail(w, r, badParam("where", "at most 8 values"))
		return
	}
	if vs := query["order"]; len(vs) > 0 {
		v_order := vs[0]
		params.Order = &v_order
	}
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.RecordsQuery(ctx, collection, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveRecordsInsert(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern15), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, nil, 0); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.RecordsInsert(ctx, collection, body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 201, res)
}

func serveRecordsGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern16), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	id := pv[1]
	if err := checkPattern("id", id, pattern17); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.RecordsGet(ctx, collection, id)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveRecordsReplace(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern18), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	id := pv[1]
	if err := checkPattern("id", id, pattern19); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, nil, 0); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.RecordsReplaceParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	res, err := h.srv.RecordsReplace(ctx, collection, id, body, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveRecordsPatch(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern20), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	id := pv[1]
	if err := checkPattern("id", id, pattern21); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, nil, 0); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.RecordsPatchParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	res, err := h.srv.RecordsPatch(ctx, collection, id, body, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	setETag(w, res.ETag)
	writeJSON(w, 200, res)
}

func serveRecordsDelete(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	collection := pv[0]
	if err := firstError(checkPattern("collection", collection, pattern22), checkLength("collection", collection, -1, 64)); err != nil {
		h.fail(w, r, err)
		return
	}
	id := pv[1]
	if err := checkPattern("id", id, pattern23); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.RecordsDeleteParams
	if vs := r.Header.Values("If-Match"); len(vs) > 0 {
		v_if_match := vs[0]
		params.IfMatch = &v_if_match
	}
	if err := h.srv.RecordsDelete(ctx, collection, id, params); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveAssetsUpload(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.AssetsUploadParams
	query := r.URL.Query()
	if vs := query["kind"]; len(vs) > 0 {
		v_kind := helm.AssetKind(vs[0])
		if err := checkEnum("kind", string(v_kind), []string{"image", "video", "audio", "other"}); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Kind = v_kind
	} else {
		h.fail(w, r, badParam("kind", "is required"))
		return
	}
	if vs := query["filename"]; len(vs) > 0 {
		v_filename := vs[0]
		if err := checkLength("filename", v_filename, -1, 255); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Filename = &v_filename
	}
	if vs := query["pinned"]; len(vs) > 0 {
		v_pinned, err := strconv.ParseBool(vs[0])
		if err != nil {
			h.fail(w, r, badParam("pinned", "must be true or false"))
			return
		}
		params.Pinned = &v_pinned
	}
	if vs := query["width"]; len(vs) > 0 {
		v_width, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("width", "must be an integer"))
			return
		}
		if err := checkRange("width", float64(v_width), ptrFloat(1), nil, nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Width = &v_width
	}
	if vs := query["height"]; len(vs) > 0 {
		v_height, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("height", "must be an integer"))
			return
		}
		if err := checkRange("height", float64(v_height), ptrFloat(1), nil, nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Height = &v_height
	}
	if vs := query["duration_s"]; len(vs) > 0 {
		v_duration_s, err := strconv.ParseFloat(vs[0], 64)
		if err != nil {
			h.fail(w, r, badParam("duration_s", "must be a number"))
			return
		}
		if err := checkRange("duration_s", float64(v_duration_s), nil, nil, ptrFloat(0)); err != nil {
			h.fail(w, r, err)
			return
		}
		params.DurationS = &v_duration_s
	}
	if vs := query["fps"]; len(vs) > 0 {
		v_fps, err := strconv.ParseFloat(vs[0], 64)
		if err != nil {
			h.fail(w, r, badParam("fps", "must be a number"))
			return
		}
		if err := checkRange("fps", float64(v_fps), nil, nil, ptrFloat(0)); err != nil {
			h.fail(w, r, err)
			return
		}
		params.FPS = &v_fps
	}
	res, created, err := h.srv.AssetsUpload(ctx, r.Body, r.Header.Get("Content-Type"), r.ContentLength, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	status := http.StatusOK
	if created {
		status = http.StatusCreated
	}
	writeJSON(w, status, res)
}

func serveAssetsAdopt(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var body helm.AdoptRequest
	if err := readBody(w, r, &body, []string{"kind", "path"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateAdoptRequest(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, created, err := h.srv.AssetsAdopt(ctx, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	status := http.StatusOK
	if created {
		status = http.StatusCreated
	}
	writeJSON(w, status, res)
}

func serveAssetsRead(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern24); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.AssetsReadParams
	if vs := r.Header.Values("Range"); len(vs) > 0 {
		v_range := vs[0]
		params.Range = &v_range
	}
	if err := h.srv.AssetsRead(ctx, w, r, id, params); err != nil {
		h.fail(w, r, err)
	}
}

func serveAssetsThumb(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern25); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.AssetsThumbParams
	query := r.URL.Query()
	if vs := query["w"]; len(vs) > 0 {
		v_w, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("w", "must be an integer"))
			return
		}
		if err := checkEnum("w", strconv.FormatFloat(float64(v_w), 'g', -1, 64), []string{"320"}); err != nil {
			h.fail(w, r, err)
			return
		}
		params.W = &v_w
	}
	if err := h.srv.AssetsThumb(ctx, w, r, id, params); err != nil {
		h.fail(w, r, err)
	}
}

func serveAssetsLineage(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern26); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.AssetsLineageParams
	query := r.URL.Query()
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.AssetsLineage(ctx, id, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveGalleryAdd(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var body helm.ItemCreate
	if err := readBody(w, r, &body, []string{"asset_id", "kind", "params"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateItemCreate(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.GalleryAdd(ctx, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 201, res)
}

func serveGalleryQuery(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.GalleryQueryParams
	query := r.URL.Query()
	if vs := query["scope"]; len(vs) > 0 {
		v_scope := vs[0]
		if err := checkEnum("scope", v_scope, []string{"self", "all"}); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Scope = &v_scope
	}
	if vs := query["studio"]; len(vs) > 0 {
		v_studio := vs[0]
		if err := checkPattern("studio", v_studio, pattern31); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Studio = &v_studio
	}
	if vs := query["kind"]; len(vs) > 0 {
		v_kind := helm.AssetKind(vs[0])
		if err := checkEnum("kind", string(v_kind), []string{"image", "video", "audio", "other"}); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Kind = &v_kind
	}
	params.Tag = query["tag"]
	if vs := query["session_id"]; len(vs) > 0 {
		v_session_id := vs[0]
		if err := checkPattern("session_id", v_session_id, pattern32); err != nil {
			h.fail(w, r, err)
			return
		}
		params.SessionID = &v_session_id
	}
	if vs := query["starred"]; len(vs) > 0 {
		v_starred, err := strconv.ParseBool(vs[0])
		if err != nil {
			h.fail(w, r, badParam("starred", "must be true or false"))
			return
		}
		params.Starred = &v_starred
	}
	if vs := query["asset_id"]; len(vs) > 0 {
		v_asset_id := vs[0]
		if err := checkPattern("asset_id", v_asset_id, pattern33); err != nil {
			h.fail(w, r, err)
			return
		}
		params.AssetID = &v_asset_id
	}
	if vs := query["since"]; len(vs) > 0 {
		v_since, err := time.Parse(time.RFC3339Nano, vs[0])
		if err != nil {
			h.fail(w, r, badParam("since", "must be an RFC 3339 time"))
			return
		}
		params.Since = &v_since
	}
	if vs := query["until"]; len(vs) > 0 {
		v_until, err := time.Parse(time.RFC3339Nano, vs[0])
		if err != nil {
			h.fail(w, r, badParam("until", "must be an RFC 3339 time"))
			return
		}
		params.Until = &v_until
	}
	if vs := query["q"]; len(vs) > 0 {
		v_q := vs[0]
		if err := checkLength("q", v_q, -1, 500); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Q = &v_q
	}
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.GalleryQuery(ctx, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveGalleryGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern34); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.GalleryGet(ctx, id)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveGalleryUpdate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern35); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, []string{"title", "starred", "tags"}, 1); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.GalleryUpdate(ctx, id, body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveGalleryDelete(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern36); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.GalleryDelete(ctx, id); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveGalleryLineage(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern37); err != nil {
		h.fail(w, r, err)
		return
	}
	var params helm.GalleryLineageParams
	query := r.URL.Query()
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.GalleryLineage(ctx, id, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveHandoffSend(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var body helm.HandoffRequest
	if err := readBody(w, r, &body, []string{"item_id", "to_studio"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateHandoffRequest(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.HandoffSend(ctx, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 201, res)
}

func serveInboxList(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.InboxListParams
	query := r.URL.Query()
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.InboxList(ctx, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveInboxConsume(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern41); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.InboxConsume(ctx, id); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveJobsList(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var params helm.JobsListParams
	query := r.URL.Query()
	if vs := query["limit"]; len(vs) > 0 {
		v_limit, err := strconv.ParseInt(vs[0], 10, 64)
		if err != nil {
			h.fail(w, r, badParam("limit", "must be an integer"))
			return
		}
		if err := checkRange("limit", float64(v_limit), ptrFloat(1), ptrFloat(200), nil); err != nil {
			h.fail(w, r, err)
			return
		}
		params.Limit = &v_limit
	}
	if vs := query["cursor"]; len(vs) > 0 {
		v_cursor := vs[0]
		params.Cursor = &v_cursor
	}
	res, err := h.srv.JobsList(ctx, params)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveJobsCreate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	var body helm.TaskCreate
	if err := readBody(w, r, &body, []string{}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateTaskCreate(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.JobsCreate(ctx, &body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 201, res)
}

func serveJobsGet(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern42); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.JobsGet(ctx, id)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveJobsUpdate(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern43); err != nil {
		h.fail(w, r, err)
		return
	}
	body := map[string]any{}
	if err := readObject(w, r, &body, []string{"state", "progress_num", "progress_den", "last_error"}, 1); err != nil {
		h.fail(w, r, err)
		return
	}
	res, err := h.srv.JobsUpdate(ctx, id, body)
	if err != nil {
		h.fail(w, r, err)
		return
	}
	writeJSON(w, 200, res)
}

func serveJobsCancel(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern44); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.JobsCancel(ctx, id); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

func serveJobsLogs(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern45); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.JobsLogs(ctx, w, r, id); err != nil {
		h.fail(w, r, err)
	}
}

func serveJobsAppendLog(ctx context.Context, h *Handler, w http.ResponseWriter, r *http.Request, pv []string) {
	id := pv[0]
	if err := checkPattern("id", id, pattern46); err != nil {
		h.fail(w, r, err)
		return
	}
	var body helm.LogAppend
	if err := readBody(w, r, &body, []string{"lines"}); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := validateLogAppend(&body); err != nil {
		h.fail(w, r, err)
		return
	}
	if err := h.srv.JobsAppendLog(ctx, id, &body); err != nil {
		h.fail(w, r, err)
		return
	}
	w.WriteHeader(204)
}

var pattern0 = regexp.MustCompile("^[a-z][a-z0-9_.-]{0,63}$")

var pattern1 = regexp.MustCompile("^[a-z][a-z0-9_.-]{0,63}$")

var pattern2 = regexp.MustCompile("^[A-Za-z0-9_.:-]{1,200}$")

var pattern3 = regexp.MustCompile("^[a-z][a-z0-9_.-]{0,63}$")

var pattern4 = regexp.MustCompile("^[A-Za-z0-9_.:-]{1,200}$")

var pattern5 = regexp.MustCompile("^[a-z][a-z0-9_.-]{0,63}$")

var pattern6 = regexp.MustCompile("^[A-Za-z0-9_.:-]{1,200}$")

var pattern7 = regexp.MustCompile("^[a-z][a-z0-9_.-]{0,63}$")

var pattern8 = regexp.MustCompile("^[A-Za-z0-9_.:-]{1,200}$")

func validateSessionCreate(v *helm.SessionCreate) error {
	if err := checkLength("name", v.Name, 1, 200); err != nil {
		return err
	}
	return nil
}

var pattern9 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern10 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern11 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern12 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

func validateSessionDuplicate(v *helm.SessionDuplicate) error {
	if err := checkLength("name", v.Name, 1, 200); err != nil {
		return err
	}
	return nil
}

var pattern13 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern14 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern15 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern16 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern17 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern18 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern19 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern20 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern21 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern22 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

var pattern23 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

func validateAdoptRequest(v *helm.AdoptRequest) error {
	if err := checkEnum("kind", string(v.Kind), []string{"image", "video", "audio", "other"}); err != nil {
		return err
	}
	if v.Width != nil {
		if err := checkRange("width", float64((*v.Width)), ptrFloat(1), nil, nil); err != nil {
			return err
		}
	}
	if v.Height != nil {
		if err := checkRange("height", float64((*v.Height)), ptrFloat(1), nil, nil); err != nil {
			return err
		}
	}
	if v.DurationS != nil {
		if err := checkRange("duration_s", float64((*v.DurationS)), nil, nil, ptrFloat(0)); err != nil {
			return err
		}
	}
	if v.FPS != nil {
		if err := checkRange("fps", float64((*v.FPS)), nil, nil, ptrFloat(0)); err != nil {
			return err
		}
	}
	return nil
}

var pattern24 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern25 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern26 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern27 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern28 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern29 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern30 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

func validateItemInput(v *helm.ItemInput) error {
	if err := checkPattern("asset_id", v.AssetID, pattern29); err != nil {
		return err
	}
	if err := firstError(checkPattern("role", v.Role, pattern30), checkLength("role", v.Role, -1, 64)); err != nil {
		return err
	}
	return nil
}

func validateItemCreate(v *helm.ItemCreate) error {
	if err := checkEnum("kind", string(v.Kind), []string{"image", "video", "audio", "other"}); err != nil {
		return err
	}
	if err := checkPattern("asset_id", v.AssetID, pattern27); err != nil {
		return err
	}
	if v.Title != nil {
		if err := checkLength("title", (*v.Title), -1, 500); err != nil {
			return err
		}
	}
	if v.SessionID != nil {
		if err := checkPattern("session_id", (*v.SessionID), pattern28); err != nil {
			return err
		}
	}
	for i := range v.Inputs {
		if err := validateItemInput(&v.Inputs[i]); err != nil {
			return err
		}
	}
	if err := checkItems("tags", len(v.Tags), -1, 32); err != nil {
		return err
	}
	for _, x := range v.Tags {
		if err := checkLength("tags", x, 1, 64); err != nil {
			return err
		}
	}
	return nil
}

var pattern31 = regexp.MustCompile("^[a-z][a-z0-9-]{1,38}[a-z0-9]$")

var pattern32 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern33 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern34 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern35 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern36 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern37 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern38 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern39 = regexp.MustCompile("^[a-z][a-z0-9-]{1,38}[a-z0-9]$")

var pattern40 = regexp.MustCompile("^[a-z][a-z0-9_]*$")

func validateHandoffRequest(v *helm.HandoffRequest) error {
	if err := checkPattern("item_id", v.ItemID, pattern38); err != nil {
		return err
	}
	if err := checkPattern("to_studio", v.ToStudio, pattern39); err != nil {
		return err
	}
	if v.Role != nil {
		if err := firstError(checkPattern("role", (*v.Role), pattern40), checkLength("role", (*v.Role), -1, 64)); err != nil {
			return err
		}
	}
	return nil
}

var pattern41 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

func validateTaskCreate(v *helm.TaskCreate) error {
	if v.State != nil {
		if err := checkEnum("state", (*v.State), []string{"queued", "running"}); err != nil {
			return err
		}
	}
	if v.SubjectKind != nil {
		if err := checkLength("subject_kind", (*v.SubjectKind), -1, 64); err != nil {
			return err
		}
	}
	if v.SubjectID != nil {
		if err := checkLength("subject_id", (*v.SubjectID), -1, 200); err != nil {
			return err
		}
	}
	if v.ProgressNum != nil {
		if err := checkRange("progress_num", float64((*v.ProgressNum)), ptrFloat(0), nil, nil); err != nil {
			return err
		}
	}
	if v.ProgressDen != nil {
		if err := checkRange("progress_den", float64((*v.ProgressDen)), ptrFloat(0), nil, nil); err != nil {
			return err
		}
	}
	return nil
}

var pattern42 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern43 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern44 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern45 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

var pattern46 = regexp.MustCompile("^[0-9A-HJKMNP-TV-Z]{26}$")

func validateLogAppend(v *helm.LogAppend) error {
	if err := checkItems("lines", len(v.Lines), 1, 1000); err != nil {
		return err
	}
	for _, x := range v.Lines {
		if err := checkLength("lines", x, -1, 16384); err != nil {
			return err
		}
	}
	return nil
}
