// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.
// The launcher's browser client: the launcher-tagged operations of
// api/openapi.yaml (docs/decisions.md M6 Q12). Served with the launcher's own
// page, never under /sdk/v1/. Method names and semantics are the runtime
// SDK's, and so is the error shape, which comes from its transport.

import { HelmError, Transport } from "/sdk/v1/runtime/transport.js";

export { HelmError };

export const API_VERSION = "1.0.0";

/** The assets group. */
export class AssetsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Exactly which assets reclaim would delete, and the bytes freed. (GET /assets:reclaim) */
  reclaimPreview() {
    return this.t.request("GET", "/assets:reclaim", { query: {}, headers: {}, expect: "json" });
  }

  /** Delete exactly the previewed set. (POST /assets:reclaim) */
  reclaim(body) {
    return this.t.request("POST", "/assets:reclaim", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** The asset's bytes, with Range. (GET /launcher/assets/{id}) */
  read(id, params = {}) {
    return this.t.request("GET", "/launcher/assets/" + encodeURIComponent(id), { query: {}, headers: {"Range": params.range}, expect: "raw" });
  }

  /** A thumbnail, generated once and cached. (GET /launcher/assets/{id}/thumb) */
  thumb(id, params = {}) {
    return this.t.request("GET", "/launcher/assets/" + encodeURIComponent(id) + "/thumb", { query: {"w": params.w}, headers: {}, expect: "raw" });
  }
}

/** The jobs group. */
export class JobsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every studio's install, build, download, update, export and uninstall jobs, newest first. (GET /launcher/jobs) */
  list(params = {}) {
    return this.t.request("GET", "/launcher/jobs", { query: {"studio": params.studio, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One lifecycle job, with its steps. A task job is 404. (GET /launcher/jobs/{id}) */
  get(id) {
    return this.t.request("GET", "/launcher/jobs/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Cancel an install, build, download or uninstall. (POST /launcher/jobs/{id}:cancel) */
  cancel(id) {
    return this.t.request("POST", "/launcher/jobs/" + encodeURIComponent(id) + ":cancel", { query: {}, headers: {}, expect: "empty" });
  }

  /** A lifecycle job's build log as server-sent events. A task job is 404. (GET /launcher/jobs/{id}/logs) */
  logs(id) {
    return this.t.request("GET", "/launcher/jobs/" + encodeURIComponent(id) + "/logs", { query: {}, headers: {}, expect: "sse" });
  }
}

/** The gallery group. */
export class GalleryGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every studio's items, newest first. (GET /launcher/gallery/items) */
  query(params = {}) {
    return this.t.request("GET", "/launcher/gallery/items", { query: {"studio": params.studio, "kind": params.kind, "tag": params.tag, "starred": params.starred, "asset_id": params.assetId, "since": params.since, "until": params.until, "q": params.q, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }
}

/** The timeline group. */
export class TimelineGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every sequence, newest first. (GET /launcher/timeline) */
  list(params = {}) {
    return this.t.request("GET", "/launcher/timeline", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** Create a sequence the launcher owns. (POST /launcher/timeline) */
  create(body) {
    return this.t.request("POST", "/launcher/timeline", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Add one asset to the end of a track. (POST /launcher/timeline:append) */
  append(body) {
    return this.t.request("POST", "/launcher/timeline:append", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** One sequence, whichever studio made it. (GET /launcher/timeline/{id}) */
  get(id) {
    return this.t.request("GET", "/launcher/timeline/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Edit a sequence. Every edit is a revision. (PATCH /launcher/timeline/{id}) */
  update(id, body, params = {}) {
    return this.t.request("PATCH", "/launcher/timeline/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/merge-patch+json" });
  }

  /** Write an earlier revision back as the newest one. (POST /launcher/timeline/{id}:revert) */
  revert(id, body, params = {}) {
    return this.t.request("POST", "/launcher/timeline/" + encodeURIComponent(id) + ":revert", { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The studios group. */
export class StudiosGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The library — every studio this machine knows about, from every source, ordered by id. (GET /studios) */
  list(params = {}) {
    return this.t.request("GET", "/studios", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One studio. (GET /studios/{id}) */
  get(id) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Clone at the pinned ref, run build[], fetch required weights. (POST /studios/{id}:install) */
  install(id, params = {}) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":install", { query: {"approval": params.approval}, headers: {}, expect: "json" });
  }

  /** Install again, resuming at the first step that has not succeeded. The same operation as :install. (POST /studios/{id}:retry) */
  retry(id, params = {}) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":retry", { query: {"approval": params.approval}, headers: {}, expect: "json" });
  }

  /** Fetch the manifest's ref again and rebuild at its tip. (POST /studios/{id}:update) */
  update(id, params = {}) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":update", { query: {"approval": params.approval}, headers: {}, expect: "json" });
  }

  /** Ask the repository where its ref points now. (POST /studios/{id}:check-update) */
  checkUpdate(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":check-update", { query: {}, headers: {}, expect: "json" });
  }

  /** Stop the group and remove the checkout helmstudio cloned. Weights and data are kept. (POST /studios/{id}:uninstall) */
  uninstall(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":uninstall", { query: {}, headers: {}, expect: "json" });
  }

  /** Start the process group in dependency order, health-gating each member. (POST /studios/{id}:launch) */
  launch(id, params = {}) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":launch", { query: {"approval": params.approval, "preempt": params.preempt}, headers: {}, expect: "json" });
  }

  /** SIGTERM the group in reverse dependency order, SIGKILL after the grace period. (POST /studios/{id}:stop) */
  stop(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":stop", { query: {}, headers: {}, expect: "json" });
  }

  /** The studio's current or most recent process group. (GET /studios/{id}/processes) */
  processes(id) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/processes", { query: {}, headers: {}, expect: "json" });
  }

  /** The studio's retained run logs, newest first. (GET /studios/{id}/logs) */
  logFiles(id, params = {}) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/logs", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One process's output as server-sent events. (GET /studios/{id}/processes/{name}/logs) */
  processLog(id, name, params = {}) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/processes/" + encodeURIComponent(name) + "/logs", { query: {}, headers: {"Last-Event-ID": params.lastEventId}, expect: "sse" });
  }

  /** The resolved manifest text, with its digest, source and file. (GET /studios/{id}/manifest) */
  manifest(id) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/manifest", { query: {}, headers: {}, expect: "json" });
  }

  /** What would run, and the digest that authorises it. (GET /studios/{id}/approval) */
  approval(id, params = {}) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/approval", { query: {"for": params.for}, headers: {}, expect: "json" });
  }

  /** Choose which of a studio's selectable weights it launches with. (PUT /studios/{id}/selection) */
  select(id, body) {
    return this.t.request("PUT", "/studios/" + encodeURIComponent(id) + "/selection", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The weights group. */
export class WeightsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Use a directory the user already has for a declared weight, instead of downloading. (POST /studios/{id}/weights/{name}:link) */
  link(id, name, body) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + "/weights/" + encodeURIComponent(name) + ":link", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Download an optional weight. (POST /studios/{id}/weights/{name}:fetch) */
  fetch(id, name) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + "/weights/" + encodeURIComponent(name) + ":fetch", { query: {}, headers: {}, expect: "json" });
  }
}

/** The manifests group. */
export class ManifestsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Validate manifest or registry-entry text. Writes nothing. (POST /launcher/manifests:validate) */
  validate(body) {
    return this.t.request("POST", "/launcher/manifests:validate", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Apply one field edit to manifest text, keeping comments and key order. Writes nothing. (POST /launcher/manifests:edit) */
  edit(body) {
    return this.t.request("POST", "/launcher/manifests:edit", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Save a local manifest or pointer, creating the Local entry that overrides lower sources. (PUT /launcher/manifests/{id}) */
  save(id, body, params = {}) {
    return this.t.request("PUT", "/launcher/manifests/" + encodeURIComponent(id), { query: {}, headers: {"If-Match": params.ifMatch}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Revert a local manifest, so the source beneath it resolves again. (DELETE /launcher/manifests/{id}) */
  revert(id) {
    return this.t.request("DELETE", "/launcher/manifests/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Copy an entry to a Local manifest under a new id, changing the id and nothing else. (POST /launcher/manifests/{id}:duplicate) */
  duplicate(id, body) {
    return this.t.request("POST", "/launcher/manifests/" + encodeURIComponent(id) + ":duplicate", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Report on manifests given as text or fetched from a URL, then add them on confirmation. (POST /launcher/manifests:import) */
  import(body) {
    return this.t.request("POST", "/launcher/manifests:import", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The repositories group. */
export class RepositoriesGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Read a repository's manifest without cloning or installing it. Writes nothing. (POST /launcher/repositories:read) */
  read(body) {
    return this.t.request("POST", "/launcher/repositories:read", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The models group. */
export class ModelsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every model artifact, newest first, with the studios bound to it. (GET /models) */
  list(params = {}) {
    return this.t.request("GET", "/models", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One artifact, with the one-item reclaim preview a DELETE must confirm when it is an unused download. (GET /models/{id}) */
  get(id) {
    return this.t.request("GET", "/models/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Unlink a linked artifact, or reclaim an unused download with the confirm from its preview. (DELETE /models/{id}) */
  delete(id, params = {}) {
    return this.t.request("DELETE", "/models/" + encodeURIComponent(id), { query: {"confirm": params.confirm}, headers: {}, expect: "empty" });
  }

  /** Exactly which downloads reclaim would delete — managed artifacts no studio is bound to. (GET /models:reclaim) */
  reclaimPreview() {
    return this.t.request("GET", "/models:reclaim", { query: {}, headers: {}, expect: "json" });
  }

  /** Delete exactly the previewed set, or nothing (409 preview_changed with the current preview). (POST /models:reclaim) */
  reclaim(body) {
    return this.t.request("POST", "/models:reclaim", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** The models directory and the free space on its volume. (GET /models:disk) */
  disk() {
    return this.t.request("GET", "/models:disk", { query: {}, headers: {}, expect: "json" });
  }
}

/** The settings group. */
export class SettingsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The launcher's theme. (GET /launcher/settings/theme) */
  theme() {
    return this.t.request("GET", "/launcher/settings/theme", { query: {}, headers: {}, expect: "json" });
  }

  /** Set the launcher's theme; every running studio follows it. (PUT /launcher/settings/theme) */
  setTheme(body) {
    return this.t.request("PUT", "/launcher/settings/theme", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Whether a Hugging Face token is stored, and when it was added. Never the token itself. (GET /launcher/settings/huggingface-token) */
  huggingFaceToken() {
    return this.t.request("GET", "/launcher/settings/huggingface-token", { query: {}, headers: {}, expect: "json" });
  }

  /** Store or replace the Hugging Face token. (PUT /launcher/settings/huggingface-token) */
  setHuggingFaceToken(body) {
    return this.t.request("PUT", "/launcher/settings/huggingface-token", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Remove the stored Hugging Face token. (DELETE /launcher/settings/huggingface-token) */
  deleteHuggingFaceToken() {
    return this.t.request("DELETE", "/launcher/settings/huggingface-token", { query: {}, headers: {}, expect: "empty" });
  }

  /** This daemon's version, the API and SDK majors it serves, and the directories it uses. (GET /launcher/settings/about) */
  about() {
    return this.t.request("GET", "/launcher/settings/about", { query: {}, headers: {}, expect: "json" });
  }
}

/** One property per launcher group. */
export class LauncherClient {
  constructor(transport) {
    this.assets = new AssetsGroup(transport);
    this.jobs = new JobsGroup(transport);
    this.gallery = new GalleryGroup(transport);
    this.timeline = new TimelineGroup(transport);
    this.studios = new StudiosGroup(transport);
    this.weights = new WeightsGroup(transport);
    this.manifests = new ManifestsGroup(transport);
    this.repositories = new RepositoriesGroup(transport);
    this.models = new ModelsGroup(transport);
    this.settings = new SettingsGroup(transport);
  }
}

// connect returns a client for the launcher API on this origin. The launcher
// holds no token: its operations are the ones the daemon serves to its own
// page, guarded by the Host and Origin checks rather than by a bearer token.
export function connect({ base = "/api/v1", fetch } = {}) {
  return new LauncherClient(new Transport(base, undefined, { fetch }));
}
