// Code generated by api/gen from api/openapi.yaml. DO NOT EDIT.
// The launcher's browser client: the launcher-tagged operations of
// api/openapi.yaml (docs/decisions.md M6 Q12). Served with the launcher's own
// page, never under /sdk/v1/. Method names and semantics are the runtime
// SDK's, and so is the error shape, which comes from its transport.

import { HelmError, Transport } from "/sdk/v1/runtime/transport.js";

export { HelmError };

export const API_VERSION = "1.0.0";

/** The assets group. */
export class AssetsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Exactly which assets reclaim would delete, and the bytes freed. (GET /assets:reclaim) */
  reclaimPreview() {
    return this.t.request("GET", "/assets:reclaim", { query: {}, headers: {}, expect: "json" });
  }

  /** Delete exactly the previewed set. (POST /assets:reclaim) */
  reclaim(body) {
    return this.t.request("POST", "/assets:reclaim", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The jobs group. */
export class JobsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every studio's install, build, download, update, export and uninstall jobs, newest first. (GET /launcher/jobs) */
  list(params = {}) {
    return this.t.request("GET", "/launcher/jobs", { query: {"studio": params.studio, "limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One lifecycle job, with its steps. A task job is 404. (GET /launcher/jobs/{id}) */
  get(id) {
    return this.t.request("GET", "/launcher/jobs/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Cancel an install, build, download or uninstall. (POST /launcher/jobs/{id}:cancel) */
  cancel(id) {
    return this.t.request("POST", "/launcher/jobs/" + encodeURIComponent(id) + ":cancel", { query: {}, headers: {}, expect: "empty" });
  }

  /** A lifecycle job's build log as server-sent events. A task job is 404. (GET /launcher/jobs/{id}/logs) */
  logs(id) {
    return this.t.request("GET", "/launcher/jobs/" + encodeURIComponent(id) + "/logs", { query: {}, headers: {}, expect: "sse" });
  }
}

/** The studios group. */
export class StudiosGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The studios this daemon knows, with install and process state, ordered by id. (GET /studios) */
  list(params = {}) {
    return this.t.request("GET", "/studios", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One studio. (GET /studios/{id}) */
  get(id) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Clone at the pinned ref, run build[], fetch required weights. (POST /studios/{id}:install) */
  install(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":install", { query: {}, headers: {}, expect: "json" });
  }

  /** Install again, resuming at the first step that has not succeeded. The same operation as :install. (POST /studios/{id}:retry) */
  retry(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":retry", { query: {}, headers: {}, expect: "json" });
  }

  /** Stop the group and remove the checkout helmstudio cloned. Weights and data are kept. (POST /studios/{id}:uninstall) */
  uninstall(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":uninstall", { query: {}, headers: {}, expect: "json" });
  }

  /** Start the process group in dependency order, health-gating each member. (POST /studios/{id}:launch) */
  launch(id, params = {}) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":launch", { query: {"preempt": params.preempt}, headers: {}, expect: "json" });
  }

  /** SIGTERM the group in reverse dependency order, SIGKILL after the grace period. (POST /studios/{id}:stop) */
  stop(id) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + ":stop", { query: {}, headers: {}, expect: "json" });
  }

  /** The studio's current or most recent process group. (GET /studios/{id}/processes) */
  processes(id) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/processes", { query: {}, headers: {}, expect: "json" });
  }

  /** The studio's retained run logs, newest first. (GET /studios/{id}/logs) */
  logFiles(id, params = {}) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/logs", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One process's output as server-sent events. (GET /studios/{id}/processes/{name}/logs) */
  processLog(id, name, params = {}) {
    return this.t.request("GET", "/studios/" + encodeURIComponent(id) + "/processes/" + encodeURIComponent(name) + "/logs", { query: {}, headers: {"Last-Event-ID": params.lastEventId}, expect: "sse" });
  }
}

/** The weights group. */
export class WeightsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Use a directory the user already has for a declared weight, instead of downloading. (POST /studios/{id}/weights/{name}:link) */
  link(id, name, body) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + "/weights/" + encodeURIComponent(name) + ":link", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }

  /** Download an optional weight. (POST /studios/{id}/weights/{name}:fetch) */
  fetch(id, name) {
    return this.t.request("POST", "/studios/" + encodeURIComponent(id) + "/weights/" + encodeURIComponent(name) + ":fetch", { query: {}, headers: {}, expect: "json" });
  }
}

/** The models group. */
export class ModelsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** Every model artifact, newest first, with the studios bound to it. (GET /models) */
  list(params = {}) {
    return this.t.request("GET", "/models", { query: {"limit": params.limit, "cursor": params.cursor}, headers: {}, expect: "json" });
  }

  /** One artifact, with the one-item reclaim preview a DELETE must confirm when it is an unused download. (GET /models/{id}) */
  get(id) {
    return this.t.request("GET", "/models/" + encodeURIComponent(id), { query: {}, headers: {}, expect: "json" });
  }

  /** Unlink a linked artifact, or reclaim an unused download with the confirm from its preview. (DELETE /models/{id}) */
  delete(id, params = {}) {
    return this.t.request("DELETE", "/models/" + encodeURIComponent(id), { query: {"confirm": params.confirm}, headers: {}, expect: "empty" });
  }

  /** Exactly which downloads reclaim would delete — managed artifacts no studio is bound to. (GET /models:reclaim) */
  reclaimPreview() {
    return this.t.request("GET", "/models:reclaim", { query: {}, headers: {}, expect: "json" });
  }

  /** Delete exactly the previewed set, or nothing (409 preview_changed with the current preview). (POST /models:reclaim) */
  reclaim(body) {
    return this.t.request("POST", "/models:reclaim", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** The settings group. */
export class SettingsGroup {
  constructor(transport) {
    this.t = transport;
  }

  /** The launcher's theme. (GET /launcher/settings/theme) */
  theme() {
    return this.t.request("GET", "/launcher/settings/theme", { query: {}, headers: {}, expect: "json" });
  }

  /** Set the launcher's theme; every running studio follows it. (PUT /launcher/settings/theme) */
  setTheme(body) {
    return this.t.request("PUT", "/launcher/settings/theme", { query: {}, headers: {}, expect: "json", json: body, contentType: "application/json" });
  }
}

/** One property per launcher group. */
export class LauncherClient {
  constructor(transport) {
    this.assets = new AssetsGroup(transport);
    this.jobs = new JobsGroup(transport);
    this.studios = new StudiosGroup(transport);
    this.weights = new WeightsGroup(transport);
    this.models = new ModelsGroup(transport);
    this.settings = new SettingsGroup(transport);
  }
}

// connect returns a client for the launcher API on this origin. The launcher
// holds no token: its operations are the ones the daemon serves to its own
// page, guarded by the Host and Origin checks rather than by a bearer token.
export function connect({ base = "/api/v1", fetch } = {}) {
  return new LauncherClient(new Transport(base, undefined, { fetch }));
}
